#!/usr/bin/env perl
#
#  Synopsis:
#	Convert a single message mail box file (elm) to json
#  Usage:
#	bio-cat btc20:d8317137cd727149c5a44b8b0b093246899d100b | eml2json
#  Note:
#	$p->readSeparator() returns empty.  not sure why.
#
use Mail::Box::Parser;

sub escape_json
{
        my $s = $_[0];

        $s =~ s/\n/\\n/g;
        $s =~ s/\t/\\t/g;
        $s =~ s/\f/\\f/g;
        $s =~ s/\r/\\r/g;
        $s =~ s/\x08/\\b/g;             # backspace
        $s =~ s/"/\\"/g;
        $s =~ s/'/\\'/g;
        return $s;
}
my $ARGC=scalar(@ARGV);
$ARGC == 1 || die "wrong argument count: got $ARGC, expected 1";
my $BLOB = escape_json($ARGV[0]);
die "blob not udig: $BLOB" unless
  $BLOB =~ /^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$/
; 

my $p = Mail::Box::Parser->new(
	file => \*STDIN,
) or die "Mail::Box::Parser->new failed: $!";

my ($where, @header)  = $p->readHeader();
my $header_count = scalar(@header);

my $default_parser_type = escape_json($p->defaultParserType());
#my ($location, $line_number) = escape_json($p->readSeparator());

my $now = `RFC3339Nano`;
die "unknown RFC3339Nano: $now" unless $now =~ /^\d\d\d\d-\d\d-\d\dT/;
chomp $now;

print <<END;
{
	"now": "$now",
	"eml_blob": "$BLOB",
	"where": $where,
	"default_parser_type": "$default_parser_type",

	"header_count": $header_count,
	"header": [
END

for (my $i = 0;  $i < $header_count;  $i++) {
	my $h = $header[$i];
	my $f = escape_json($h->[0]);
	my $v = escape_json($h->[1]);
	print qq(
			["$f",
			 "$v",
			 	$i
			]);
	print ',' if $i + 1 < $header_count;
	print "\n";
}

print <<END;
	]
}
END
