#!/bin/bash
#
#  Synopsis:
#	Run 'file --mime-encoding --brief' on blob and answer to PostgreSQL
#  Usage:
#	merge-file_mime_encoding <blob udig>
#  Exit Status:
#	0	ok
#	1	blob does not exist
#	2	file --mime-encoding output is not utf8
#	3	wrong number of command line arguments
#	4	blobio get failed
#	5	command 'file --mime-encoding --brief <blob> failed'
#	6	sql merge failed
#  Environment:
#	BLOBIO_SERVICE
#	TMPDIR
#  Note:
#	Should the LANG/LC_* variables be explicitly set to UTF8?
#

PROG=merge-file_mime_encoding

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.blob.$$
TMP_MIME_ENCODING=${TMPDIR:=/tmp}/$PROG.mime.$$

leave()
{
	rm -f $TMP_BLOB $TMP_MIME_ENCODING
}
trap leave EXIT

test $# = 1 || die 'wrong number of arguments' 3
FILE_BLOB=$1

#  fetch the blob

blobio get --udig $FILE_BLOB --service $BLOBIO_SERVICE --output-path $TMP_BLOB
STATUS=$?
test $STATUS = 1 && exit 1
test $STATUS = 0 || die "blobio get failed: exit status=$STATUS" 4

#  call 'file --mime-encoding --brief'

file --mime-encoding --brief $TMP_BLOB >$TMP_MIME_ENCODING
test $? = 0 || die "file --mime-encoding command failed: exit status=$?" 5

#  insure file output is proper utf8

is-utf8wf <$TMP_MIME_ENCODING
STATUS=$?
case $STATUS in
0)
	IS_NULL=no
	EXIT_STATUS=0
	;;
1)
	IS_NULL=yes
	EXIT_STATUS=2
	;;
*)
	die "is-utf8wf failed: exit status=$STATUS" 5
	;;
esac

if [ $IS_NULL = no ];  then

	#  stat the size of the utf8 output file

	MIME_ENCODING_SIZE=$(file-stat-size $TMP_MIME_ENCODING)
	test $? = 0 || die "file-stat-size failed: exit status=$?" 5

	#  merge file output into table fffile.file_mime_encoding

	merge-stdin-file_mime_encoding <$TMP_MIME_ENCODING		\
		$FILE_BLOB $MIME_ENCODING_SIZE	||
		   die "merge-stdin-file_mime_encoding failed: exit status=$?" 7
else
	psql --quiet --no-psqlrc <<END
INSERT INTO fffile.file_mime_encoding(
	blob,
	mime_encoding
  ) VALUES(
  	'$FILE_BLOB',
	null
  )  ON CONFLICT
  	DO NOTHING
;
END
	test $? = 0 || die "psql null insert failed: exit status=$?" 6
fi

exit $EXIT_STATUS
