#!/usr/bin/env perl
#
#  Synopsis:
#	Auto-made script /cgi-bin/schema/pdfbox, made by cgi2perl5.
#  Source Path:
#	pdfbox.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT}
;

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib/schema", "$ENV{SERVER_ROOT}/lib";

our %CGI;

require 'httpd2.d/common.pl';
$CGI{name} = 'pdfbox';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'table|dl|(?:span[.]nav)|input|(?:input[.]mytitle)|(?:mime[.]pdf)|(?:a[.]mime)|(?:iframe[.]pdf)|(?:utf8[.]pg1)|(?:dl[.]pddoc)|(?:dl[.]pdinfo)|(?:dl[.]extpg)|(?:table[.]exttsv)|(?:text[.]objdesc)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='table']
#
$CGI{GET}->{out}->{putter}->{'table'}->{name} = 'table';

#
#  BEGIN: /cgi/GET/out/putter[@name=table]/query-args
#
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{tsconf} = {
	perl5_re	=>	'[a-z0-9-]{1,32}',
	default	=>	'english',
};
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{rnorm} = {
	perl5_re	=>	'[0-9]{1,3}',
	default	=>	'14',
};
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{limit} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{offset} = {
	perl5_re	=>	'[+0-9]{1,10}',
};
#
#  END: /cgi/GET/out/putter[@name=table]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='table']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl']
#
$CGI{GET}->{out}->{putter}->{'dl'}->{name} = 'dl';
$CGI{GET}->{out}->{putter}->{'dl'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{tsconf} = {
	perl5_re	=>	'[a-z0-9-]{1,32}',
	default	=>	'english',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{rnorm} = {
	perl5_re	=>	'[0-9]{1,3}',
	default	=>	'14',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{limit} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{offset} = {
	perl5_re	=>	'[+0-9]{1,10}',
};
#
#  END: /cgi/GET/out/putter[@name=dl]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='span.nav']
#
$CGI{GET}->{out}->{putter}->{'span.nav'}->{name} = 'span.nav';
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=span.nav]/query-args
#
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{offset} = {
	perl5_re	=>	'[+0-9]{1,10}',
};
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{limit} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
#
#  END: /cgi/GET/out/putter[@name=span.nav]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='span.nav']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='input']
#
$CGI{GET}->{out}->{putter}->{'input'}->{name} = 'input';
$CGI{GET}->{out}->{putter}->{'input'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=input]/query-args
#
$CGI{GET}->{out}->{putter}->{'input'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=input]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='input.mytitle']
#
$CGI{GET}->{out}->{putter}->{'input.mytitle'}->{name} = 'input.mytitle';
$CGI{GET}->{out}->{putter}->{'input.mytitle'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=input.mytitle]/query-args
#
$CGI{GET}->{out}->{putter}->{'input.mytitle'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
};
$CGI{GET}->{out}->{putter}->{'input.mytitle'}->{'query-args'}->{arg}->{title} = {
	perl5_re	=>	'.*{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=input.mytitle]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input.mytitle']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='mime.pdf']
#
$CGI{GET}->{out}->{putter}->{'mime.pdf'}->{name} = 'mime.pdf';

#
#  BEGIN: /cgi/GET/out/putter[@name=mime.pdf]/query-args
#
$CGI{GET}->{out}->{putter}->{'mime.pdf'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=mime.pdf]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='mime.pdf']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='a.mime']
#
$CGI{GET}->{out}->{putter}->{'a.mime'}->{name} = 'a.mime';
$CGI{GET}->{out}->{putter}->{'a.mime'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=a.mime]/query-args
#
$CGI{GET}->{out}->{putter}->{'a.mime'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=a.mime]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='a.mime']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='iframe.pdf']
#
$CGI{GET}->{out}->{putter}->{'iframe.pdf'}->{name} = 'iframe.pdf';
$CGI{GET}->{out}->{putter}->{'iframe.pdf'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=iframe.pdf]/query-args
#
$CGI{GET}->{out}->{putter}->{'iframe.pdf'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=iframe.pdf]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='iframe.pdf']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='utf8.pg1']
#
$CGI{GET}->{out}->{putter}->{'utf8.pg1'}->{name} = 'utf8.pg1';
$CGI{GET}->{out}->{putter}->{'utf8.pg1'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=utf8.pg1]/query-args
#
$CGI{GET}->{out}->{putter}->{'utf8.pg1'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
$CGI{GET}->{out}->{putter}->{'utf8.pg1'}->{'query-args'}->{arg}->{len} = {
	perl5_re	=>	'\d{1,10}',
	default	=>	'65535',
};
#
#  END: /cgi/GET/out/putter[@name=utf8.pg1]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='utf8.pg1']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl.pddoc']
#
$CGI{GET}->{out}->{putter}->{'dl.pddoc'}->{name} = 'dl.pddoc';
$CGI{GET}->{out}->{putter}->{'dl.pddoc'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl.pddoc]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl.pddoc'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=dl.pddoc]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl.pddoc']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl.pdinfo']
#
$CGI{GET}->{out}->{putter}->{'dl.pdinfo'}->{name} = 'dl.pdinfo';
$CGI{GET}->{out}->{putter}->{'dl.pdinfo'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl.pdinfo]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl.pdinfo'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=dl.pdinfo]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl.pdinfo']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl.extpg']
#
$CGI{GET}->{out}->{putter}->{'dl.extpg'}->{name} = 'dl.extpg';
$CGI{GET}->{out}->{putter}->{'dl.extpg'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl.extpg]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl.extpg'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=dl.extpg]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl.extpg']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='table.exttsv']
#
$CGI{GET}->{out}->{putter}->{'table.exttsv'}->{name} = 'table.exttsv';
$CGI{GET}->{out}->{putter}->{'table.exttsv'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=table.exttsv]/query-args
#
$CGI{GET}->{out}->{putter}->{'table.exttsv'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=table.exttsv]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='table.exttsv']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='text.objdesc']
#
$CGI{GET}->{out}->{putter}->{'text.objdesc'}->{name} = 'text.objdesc';
$CGI{GET}->{out}->{putter}->{'text.objdesc'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=text.objdesc]/query-args
#
$CGI{GET}->{out}->{putter}->{'text.objdesc'}->{'query-args'}->{arg}->{name} = {
	perl5_re	=>	'^[a-z][a-z0-9_]{0,64}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=text.objdesc]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='text.objdesc']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='post.q']
#
$CGI{POST}->{in}->{putter}->{'post.q'}->{name} = 'post.q';
$CGI{POST}->{in}->{putter}->{'post.q'}->{vars}->{var}->{q} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/POST/in/putter[@name=post.q]/vars
#

#
#  END: /cgi/POST/in/putter[@name='post.q']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='post.mytitle']
#
$CGI{POST}->{in}->{putter}->{'post.mytitle'}->{name} = 'post.mytitle';
$CGI{POST}->{in}->{putter}->{'post.mytitle'}->{vars}->{var}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
};
$CGI{POST}->{in}->{putter}->{'post.mytitle'}->{vars}->{var}->{title} = {
	perl5_re	=>	'.{1,255}',
};
#
#  END: /cgi/POST/in/putter[@name=post.mytitle]/vars
#

#
#  END: /cgi/POST/in/putter[@name='post.mytitle']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
