#!/usr/bin/env perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/tag-url.
#  Source Path:
#	tag-url.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  GitHub:
#	https://github.com/jmscott/work/tree/master/httpd2
#  Note:
#	/cgi-bin/tag-url was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'tag-url';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'a|textarea|dl|(?:select[.]rppg)|(?:div[.]nav)|save|click|(?:div[.]err)|(?:select[.]host)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='a']
#
$CGI{GET}->{out}->{putter}->{'a'}->{name} = 'a';
$CGI{GET}->{out}->{putter}->{'a'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=a]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='a']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='textarea']
#
$CGI{GET}->{out}->{putter}->{'textarea'}->{name} = 'textarea';
$CGI{GET}->{out}->{putter}->{'textarea'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=textarea]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='textarea']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl']
#
$CGI{GET}->{out}->{putter}->{'dl'}->{name} = 'dl';
$CGI{GET}->{out}->{putter}->{'dl'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'10|100|1000|10000',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'[1-9]\d{0,9}',
	default	=>	'1',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{host} = {
	perl5_re	=>	'[\w.-]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=dl]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='select.rppg']
#
$CGI{GET}->{out}->{putter}->{'select.rppg'}->{name} = 'select.rppg';
$CGI{GET}->{out}->{putter}->{'select.rppg'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select.rppg]/query-args
#
$CGI{GET}->{out}->{putter}->{'select.rppg'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'10|100|1000|10000',
	default	=>	'10',
};
#
#  END: /cgi/GET/out/putter[@name=select.rppg]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select.rppg']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='div.nav']
#
$CGI{GET}->{out}->{putter}->{'div.nav'}->{name} = 'div.nav';
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=div.nav]/query-args
#
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'10|100|1000|10000',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'[1-9]\d{0,9}',
	default	=>	'1',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{host} = {
	perl5_re	=>	'[\w.-]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=div.nav]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='div.nav']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='save']
#
$CGI{GET}->{out}->{putter}->{'save'}->{name} = 'save';

#
#  BEGIN: /cgi/GET/out/putter[@name=save]/query-args
#
$CGI{GET}->{out}->{putter}->{'save'}->{'query-args'}->{arg}->{url} = {
	perl5_re	=>	'.{0,255}',
	required	=>	'yes',
};
$CGI{GET}->{out}->{putter}->{'save'}->{'query-args'}->{arg}->{title} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=save]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='save']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='click']
#
$CGI{GET}->{out}->{putter}->{'click'}->{name} = 'click';

#
#  BEGIN: /cgi/GET/out/putter[@name=click]/query-args
#
$CGI{GET}->{out}->{putter}->{'click'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,14}:[[:graph:]]{1,255}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=click]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='click']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='div.err']
#
$CGI{GET}->{out}->{putter}->{'div.err'}->{name} = 'div.err';
$CGI{GET}->{out}->{putter}->{'div.err'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=div.err]/query-args
#
$CGI{GET}->{out}->{putter}->{'div.err'}->{'query-args'}->{arg}->{err} = {
	perl5_re	=>	'[[:print:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=div.err]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='div.err']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='select.host']
#
$CGI{GET}->{out}->{putter}->{'select.host'}->{name} = 'select.host';
$CGI{GET}->{out}->{putter}->{'select.host'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select.host]/query-args
#
$CGI{GET}->{out}->{putter}->{'select.host'}->{'query-args'}->{arg}->{host} = {
	perl5_re	=>	'[\w.-]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=select.host]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select.host']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
