#!/bin/bash
#
#  Synopsis:
#	Boot a schema flowd server from either launchd, systemd or command-line
#  Usage:
#	SETSPACE_ROOT=/usr/local/setspace/opt/uspto
#	cd $SETSPACE_ROOT/schema/pdfbox
#	boot-flowd etc/pdfbox.flow
#

PROG=$(basename $0)

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 2
}

leave()
{
	log 'good bye, cruel world'
}

test $# = 1 || die 'wrong number of arguments'
FLOW=$1

log 'hello, world'
trap leave EXIT

log "flow file: $FLOW"
test -e $FLOW || die "flow file does not exist: $FLOW"

test -n "$SETSPACE_ROOT" || die "environment var not defined: SETSPACE_ROOT"
log "SETSPACE_ROOT=$SETSPACE_ROOT"

#
#  source in global $SETSPACE_ROOT/etc/profile
#
PROFILE=$SETSPACE_ROOT/etc/profile
log "source: $PROFILE"
test -r $PROFILE || die "can not read setspace profile: $PROFILE"
. $PROFILE || die "sourcing setspace profile failed: $PROFILE"

#
#  source in schema specific profile
#
PROFILE=etc/profile
log "source: $PROFILE"
test -r etc/profile || die "can not read schema profile: $PROFILE"
. $PROFILE || die "sourcing schema profile failed: $PROFILE"

#  set up gnu tools on the mac
WHICH_OS=$(uname -s)
log "operating system: $WHICH_OS"

#  on mac we require gnutools from ports distro to be install
if [ "$WHICH_OS" = Darwin ];  then
	log 'checking for gnu tools from mac ports ...'
	test -d /opt/local/libexec/gnubin || die 'port gnubin not installed'

	case "$PATH" in
	*/gnubin*)
		;;
	*)
		PATH=/opt/local/libexec/gnubin:/opt/local/bin:$PATH
		;;
	esac
fi

log "PATH=$PATH"
log "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

if [ -e run/flow.pid ];  then
	log "run/flowd.pid exists: process #$(head -1 run/flow.pid)"
	kill $(head -1 run/flow.pid)
fi

log 'clearing run/ directory of stale files ...'
find run -follow -type f -name 'flowd*' | while read ZAP_RUN;  do
	log "zap run/ file: $ZAP_RUN"
	rm $ZAP_RUN
done

INITX=sbin/launchd-flowd-init
if [ -x $INITX ];  then
	log "$INITX exists, so invoking ..."
	$INITX || die "launchd-flow-init failed: exit status=$?"
fi

log 'dumping process environment ...'
env | sort | while read E;  do
	log "$E"
done

if [ $PPID = 0 ];  then
	log 'parent pid id 0, called from init manager'
	log "execing flowd server $FLOW ..."
	flowd server $FLOW
	exec rm -f run/flowd*
fi

log "invoked from script, so forking flowd into background"
flowd server $FLOW &
BG_PID=$!
log "bg process id: $BG_PID"
