#!/bin/bash
#
#  Synopsis:
#	Cron script to reboot all setspace flow schema processes
#  Usage:
#	#  in crontab
#	SETSPACE_ROOT=/usr/local/setspace
#	LOG=$SETSPACE_ROOT/log/cron-reboot.log
#
#	@reboot $SETSPACE_ROOTsbin/cron-reboot >>$LOG 2>&1
#  Exit Status:
#	0	all flowd process rebooted
#	1	unknown error, processes may not have rebooted
#  Note:
#	Ought to attempt to boot all flowd processes instead of aborting
#	upon the first failure.
#

PROG=$(basename $0)
PKILL_PAUSE=10

log()
{
	MSG=$@
	test -n "$SCHEMA" && MSG="$SCHEMA: $MSG"
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $MSG"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

log 'hello, world'
trap leave EXIT

test -n "$SETSPACE_ROOT" ||
			die "environment variable not defined: SETSPACE_ROOT"
log "SETSPACE_ROOT=$SETSPACE_ROOT"

cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed"

if [ $USER = setspace ];  then
	log 'user is setspace, so process controled by launchd or systemd'
	log 'doing pkill -u setspace flowd'
	pkill -u setspace flowd
	log "pausing $PKILL_PAUSE seconds ..."
	sleep $PKILL_PAUSE
	run-stat-report
	exit
fi

. etc/profile
log "path to flowd executable: $(which flowd)"

#  shutdown any flowd processes

log 'killing all flowd processes ...'
kill-all-flowd || die "kill-all-flowd failed: exit status=$?"

#  boot up a flowd process for each flow file in
#  schema/$SCHEMA/etc/$SCHEMA.flow

log 'finding schemas for bootable flowd ...'
ls-boot-flowd | while read SCHEMA;  do
	log "schema: $SCHEMA"
	boot-flowd $SCHEMA || die "boot-flowd $SCHEMA failed: exit status=$?"
done

log 'all flowds started'

echo
run-stat-report
echo
