#!/bin/bash
#
#  Synopsis:
#	Cron job to "get" blobs with unknown facts and log details to spool.
#  Usage:
#	SBIN=/usr/local/setspace/sbin
#	LOG=/usr/local/setspace/log
#
#	* * * * * $SBIN/cron-rummy '-1 day' >>$LOG 2>&1
#	24 * * * * $SBIN/cron-rummy '1 week' >>$LOG 2>&1
#	01 4 * * * $SBIN/cron-rummy '1 month' >>$LOG 2>&1
#	01 5 4 * * $SBIN/cron-rummy '1 year' >>$LOG 2>&1
#  Exit Status:
#	0	ok
#	1	failed
#  Note:
#	A nice addition would be to display/log the discover time of each
#	gotten blob.
#
#	Ought to "get" a blob only once, by tracking in an associative array.
#
#	Think about adding a "what" label to the rummy detail record.
#

PROG=cron-rummy

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S'): #$$: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	rm -f $TMP_RUMMY
	log 'good bye, cruel world'
	exit
}
trap leave EXIT

log 'hello, world'

test $# = 1 || die 'wrong number of arguments'
SINCE="$1"

test -n "$SETSPACE_ROOT" || die 'env var not defined: SETSPACE_ROOT'
log "SETSPACE_ROOT=$SETSPACE_ROOT"

log "since: $SINCE"

cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed"
. etc/profile
log "BLOBIO_ROOT=$BLOBIO_ROOT"
log "BLOBIO_SERVICE=$BLOBIO_SERVICE"
test -d spool || die "directory not found: $(pwd)/spool"
SPOOL=spool/rummy.rdr

log "TMPDIR=$TMPDIR"
TMP_RUMMY=${TMPDIR:=/tmp}/$PROG-$$.udig

NOW=$(RFC3339Nano)
log "now: $NOW"

#  find the blobs with known unknowns ..

log "finding blobs discovered since $SINCE ago ..."
rummy "$SINCE" >$TMP_RUMMY || die "rummy failed: exit status=$?"
RC=$(wc -l $TMP_RUMMY | awk '{print $1}')
log "total blob count: $RC"

#  track blobio ok/no chat history count in global array

declare -a ok_no
ok_no[0]=0;
ok_no[1]=0;

#  "get" the blobs one at a time and record status in spool/rummy.rdr

while read SCH U;  do

	#  fetch the blob from the service

	blobio get --udig $U --service $BLOBIO_SERVICE >/dev/null
	STATUS=$?
	case $STATUS in
	0)
		log "<$U	$SCH"
		ok_no[0]=$(expr ${ok_no[0]} + 1)
		CHAT_HISTORY=ok
		;;
	1)
		log "?$U	$SCH"
		ok_no[1]=$(expr ${ok_no[1]} + 1)
		CHAT_HISTORY=no
		;;
	*)
		die "blobio get $U failed: exit status=$STATUS"
		;;
	esac

	#  record the detail of the rummied blob into spool/rummy.rdr

	echo "$NOW	$U	$SCH	$CHAT_HISTORY" >>$SPOOL ||
				die "echo >$SPOOL failed: exit status=$?"
done <$TMP_RUMMY
log "ok count: ${ok_no[0]}"
log "no count: ${ok_no[1]}"
