#!/usr/bin/env bash
#
#  Synopsis:
#	Find active blob request log files across all schemas
#  Usage:
#	wc -l $(find-brr)
#  Note:
#	The output path ought to be relative to the current directory,
#	enabling execution in any directory.
#

PROG=find-brr

#  match:  <schema>-1455329936.brr.  expires 2038.

ROLLED_BRR_PAT='*-[1-4][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].brr'

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test -n "$SETSPACE_ROOT" || die 'environment var not defined: SETSPACE_ROOT'
cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed"

. etc/profile

found_brr()
{
	find schema/$1/spool						\
		-maxdepth 1						\
		-name '*.brr'						\
		! -name $ROLLED_BRR_PAT					\
		-print
}

case $# in
0)
	find-schema | while read SCH;  do
		found_brr $SCH
	done
	;;
*)
	echo $@ | sed 's/  */\n/g' | while read SCH;  do
		found_brr $SCH
	done
	;;
esac
