#!/bin/bash
#
#  Synopsis:
#	Summarize today's flowd activity, particulaly faults.
#

PROG=flowd-stat

die()
{
	echo "$PROG: ERROR: $@" >&1
	exit 1
}

test -n "$SETSPACE_ROOT" || die 'env var not defined: SETSPACE_ROOT'
cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed: exit status=$?"
. etc/profile

TODAY_LOG=$(echo flowd-$(date +%a)).log

do_stat()
{
	LOG=schema/$1/log/$TODAY_LOG

	echo $1: $TODAY_LOG

	test -e $LOG || return
	test -r $LOG || die "flowd log not readable: $LOG"
	echo
	egrep ': (ERROR|WARN): ' $LOG | while read L;  do
		echo "	$L"
	done
}

case $# in
0)
	find-schema | while read SCH;  do
		do_stat $SCH
	done
	;;
*)
	while [ -n "$1" ];  do
		do_stat $1
		shift
	done
	;;
esac
