#!/bin/bash
#
#  Synopsis:
#	Summarize today's flowd activity, particulaly faults.
#

PROG=flowd-stat
STALE_MMIN=2

die()
{
	echo "$PROG: ERROR: $@" >&1
	exit 1
}

test -n "$SETSPACE_ROOT" || die 'env var not defined: SETSPACE_ROOT'
cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed: exit status=$?"
. etc/profile

TODAY_LOG=$(echo flowd-$(date +%a)).log

do_stat()
{
	LOG=schema/$1/log/$TODAY_LOG

	echo $1: $TODAY_LOG

	#  does the log file exist?

	if [ ! -e $LOG ];  then
		echo "	No log file - is flowd $1 running?"
		return
	fi
	test -r $LOG || die "flowd log not readable: $LOG"

	#  has the log been touched recenty?

	IS_STALE=$(find $LOG -mmin -$STALE_MMIN)
	test $? || die "find $LOG failed: exit status=$?"
	if [ "$IS_STALE" = '' ];  then
		echo "	Log not changed in $STALE_MMIN minutes - "	\
		     "is flowd $1 running?"
		return
	fi

	egrep ': (ERROR|WARN): ' $LOG | while read L;  do
		echo "	$L"
	done
}

case $# in
0)
	find-schema | while read SCH;  do
		do_stat $SCH
	done
	;;
*)
	while [ -n "$1" ];  do
		do_stat $1
		shift
	done
	;;
esac
