#!/bin/bash
#
#  Synopsis:
#	List running flowd servers based upin schema/*/run/flowd.pid
#  Usage:
#	ls-flowd
#  Exit Status:
#	0	flowd servers are running
#	2	unexpected error
#

die()
{
	echo "ERROR: $@" >&2
	exit 2
}

test $# = 0 || die "wrong number of arguments: got $#, expected 0"
test -n "$SETSPACE_ROOT" || die 'env var not defined: SETSPACE_ROOT'

SCHEMA=$SETSPACE_ROOT/schema
cd $SCHEMA || die "cd $SCHEMA failed: exit status=$?"

ls-flow | while read SC;  do
	SC=$(basename $SC)
	PID=$SC/run/flowd.pid
	STATE=DEAD
	#  pid exists or has run/flowd.pid been touched within 2 minutes
	if [ -e $PID -a -z "$(find $PID -mmin -2 -print)" ];  then
		STATE=ALIVE
	fi
	echo "$SC	$STATE"
done

exit 0
