#!/bin/bash
#
#  Synopsis:
#	List schemas with existing file schema/<schema>/etc/<schema>.flow
#  Usage:
#	ls-flow | xargs -L 1 boot-flowd
#  Exit Status:
#	0	ok
#	2	unexpected error
#

die()
{
	echo "ERROR: $@" >&2
	exit 2
}

test $# = 0 || die "wrong number of arguments: got $#, expected 0"
test -n "$SETSPACE_ROOT" || die 'env var not defined: SETSPACE_ROOT'

SCHEMA=$SETSPACE_ROOT/schema
cd $SCHEMA || die "cd $SCHEMA failed: exit status=$?"

find . -maxdepth 1 -type d | while read SC;  do
	test -e $SC/etc/$SC.flow && echo $(basename $SC)
done

exit 0
