#!/bin/bash
#
#  Synospsis:
#	Report of running flowd processes in schema/*/run.
#  Usage:
#	run-stat-report
#  See:
#	setspace/sbin/run-stat
#  Note:
#	Ought to consolidate this script with blobio/sbin/run-stat-report.
#
#	Sort is ignoring the second key on linux.  The pain never ends.
#
die()
{
	echo "ERROR: $@" >&2
	exit 1
}

NOW=$(date +'%s')
(
	cat <<END
Schema	Status	Up
-------------	------	------
END
	run-stat							|
		sort --key=2 --key=1 --field-separator=$'\t'		|
		while read SCHEMA STATUS START_EPOCH;  do
			case "$START_EPOCH" in
			UNKNOWN)
				DURATION=unknown
				;;
			[0-9]*)
				DURATION=$(
					duration-english		\
						$(expr $NOW - $START_EPOCH)
				)
				;;
			*)
				die "unknown start epoch: $START_EPOCH"
				;;
			esac
			echo "$SCHEMA	$STATUS	$DURATION"
		done
) | column -s '	' -t | sed 's/ *	//'
