#!/bin/bash
#
#  Synospsis:
#	Report of running flowd processes in schema/*/run.
#  Usage:
#	run-stat-report
#  See:
#	setspace/sbin/run-stat
#  Note:
#	Ought to consolidate this script with blobio/sbin/run-stat-report.
#
#	Sort is ignoring the second key on linux.  The pain never ends.
#
die()
{
	echo "ERROR: $@" >&2
	exit 1
}

NOW=$(date +'%s')
(
	cat <<END
Schema	Status	Up Time	Boot Request,Ok,Fail	Recent 10s Sample
-------------	------	------	--------------------	-----------------
END
	run-stat							|
		while read 						\
			SCHEMA STATE START_EPOCH			\
			FDR OK FLT WALL					\
			sFDR sOK sFLT sWALL; do
			case "$STATE" in
			UP)
				ORDER=1
				;;
			ZOMBIE)
				ORDER=2
				;;
			DOWN)
				ORDER=3
				;;
			OFF)
				ORDER=4
				;;
			*)
				die "unknown STATE: $STATE"
				;;
			esac
			cat <<END
$ORDER	$SCHEMA	$STATE	$START_EPOCH	$FDR	$OK	$FLT	$sFDR	$sOK	$sFLT
END
		done							|
		sort --key=1 --key=2 --field-separator=$'\t'		|
		while read ORDER SCHEMA STATE START_EPOCH		\
			   FDR OK FLT sFDR sOK sFLT;  do
			case "$START_EPOCH" in
			unknown)
				DURATION=unknown
				;;
			n/a)
				DURATION=n/a
				;;
			[0-9]*)
				DURATION=$(
					duration-english		\
						$(expr $NOW - $START_EPOCH)
				)
				;;
			*)
				die "unknown start epoch: $START_EPOCH"
				;;
			esac
			echo "$SCHEMA	$STATE	$DURATION	$FDR,$OK,$FLT	$sFDR,$sOK,$sFLT"
		done							|
		sed 's/,,/n\/a/g'					|
		sed 's/\(,n\/a\)*//g'
) | column -s '	' -t | sed 's/ *	//'
