#!/bin/bash
#
#  Synopsis:
#	List running flowd servers based upin schema/*/run/flowd.pid
#  Usage:
#	run-stat
#  Exit Status:
#	0	scanned all running processes
#	1	unexpected error
#

die()
{
	echo "ERROR: $@" >&2
	exit 1
}

test $# = 0 || die "wrong number of arguments: got $#, expected 0"
test -n "$SETSPACE_ROOT" || die 'env var not defined: SETSPACE_ROOT'

SCHEMA=$SETSPACE_ROOT/schema
cd $SCHEMA || die "cd $SCHEMA failed: exit status=$?"

ls-flow | while read SC;  do
	SC=$(basename $SC)
	PID=$SC/run/flowd.pid
	STATE=DEAD

	#  run the gauntlet on the state of the run/flowd.pid file.
	if [ -e $PID ];  then
		#  run/flowd.pid been touched within 2 minutes
		#
		#  Note:
		#	test -a alway evaluates both sides of the expression,
		#	breaking a $(find) in single invocation.
		#
		if [ -n "$(find $PID -mmin -2 -print)" ];  then
			STATE=ALIVE
		fi
	fi
	echo "$SC	$STATE"
done | sort --reverse --key=2  --key=1 --field-separator='	'

exit 0
