#!/bin/bash
#
#  Synopsis:
#	Exec a login bash shell with SETSPACE_ROOT set to $1
#  Usage:
#	SETSPACE_ROOT-bash /opt/jmscott/jmsdesk
#

die()
{
	echo "ERROR: $@" >&2
	exit 1
}

WARN()
{
	echo "WARN: $@" >&2
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
export SETSPACE_ROOT=$1
echo
echo "SETSPACE_ROOT=$SETSPACE_ROOT"

cd $SETSPACE_ROOT || die "cd failed: $SETSPACE_FAILED"
test -r etc/bash_login || die 'can not read etc/bash_login'

exec bash --init-file etc/bash_login --noprofile
