#!/bin/bash
#
#  Synopsis:
#	Manually start/stop/restart processes for SetSpace
#  Usage:
#	ssctl start	#  start the world, aborting on the first error
#	ssctl stop	#  stop all processes
#

PROG=$(basename $0)
PKILL_PAUSE=10

log()
{
	MSG=$@
	test -n "$SCHEMA" && MSG="$SCHEMA: $MSG"
	echo "$(date +'%Y/%m/%d %H:%M:%S'): $MSG"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

test $# = 1 || die "wrong arg count: expect 1, got $#"
ACTION=$1

log 'hello, world'
trap leave EXIT
log "action: $ACTION"

test -n "$SETSPACE_ROOT" ||
			die "environment variable not defined: SETSPACE_ROOT"
log "SETSPACE_ROOT=$SETSPACE_ROOT"

cd $SETSPACE_ROOT || die "cd $SETSPACE_ROOT failed"

. etc/profile
log "path to flowd: $(which flowd)"

#  shutdown any flowd processes

case "$ACTION" in
start)
	#  start up a flowd process for each flow file in
	#  schema/$SCHEMA/etc/$SCHEMA.flow

	log 'finding startable schemas ...'
	ls-start-flowd | while read SCHEMA;  do
		log "schema: $SCHEMA"
		start-flowd $SCHEMA || die "start-flowd failed: exit status=$?"
	done
	log 'all flowds started'
	;;
stop)
	log 'stopping UP/ZOMBIE flowds ...'
	stop-all-flowd || die "stop-all-flowd failed: exit status=$?"
	;;
restart)
	log 'restarting setspace process ...'
	ssctl stop && ssctl start
	;;
*)
	die "unknown action: $ACTION"
	;;
esac

echo
run-stat-report
echo
