#!/usr/bin/env bash
#
#  Synopsis:
#	ssq service <blob>, called from libexec/ssq-service
#  Note:
#	Assemble single sql instead of exec for each schema.
#

PROG=$(basename $0)
PSQL="psql
	--quiet
	--set ON_ERROR_STOP=1
	--no-psqlrc
	--tuples-only
	--no-align
	--no-readline
"

die() {
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# -eq 1 || die "wrong number of cli args: got $#, want 1"

UDIG=$1;  shift
if [[ $UDIG =~ ^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$ ]];  then
	true
else
	die "not a udig: $UDIG"
fi

cat <<END
UDig:
	$UDIG
Schema:
	Name	In Service
	------	-------
END

for SCH in $(ssq ls | sort);  do
	$PSQL <<END || die "psql failed: exit status=$?"
\f '	'
SELECT
	'	$SCH' AS name,
	EXISTS (
	  SELECT
	  	blob
	    FROM
	    	$SCH.service
	    WHERE
	    	blob = '$UDIG'
	) AS in_service
;
END
done

exit 0
