#!/usr/bin/env bash
#
#  Synopsis:
#	ssq-service <udig>, called from script bin/ssq for "service" action
#

PROG=$(basename $0)

die() {
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# -eq 1 || die "wrong number of cli args: got $#, want 1"

exec libexec/$PROG-udig $@
