#!/usr/bin/env bash
#
#  Synopsis:
#	List queryable schemas, in no particiular order
#  Usage:
#	action libexeced by command "ssq ls" 
#

#  dirs in schema/ never a schema dir.  the usual suspects.

NOT_SCHEMA='
	archive
	attic
	bin
	cache
	cgi-bin
	data
	etc
	htdocs
	include
	lib
	libexec
	log
	run
	sbin
	spool
	src
	sync
	tmp
	var
	www
'

test $# = 0 || die "wrong number of cli args: got $#, need 0"
cd schema || die "cd schema failed: exit status=$?"

FIND_OPT_IGNORE=$(
	echo "$NOT_SCHEMA"					|
	grep -v '^ *$'						|
	sed 's/.*/ ! -name &/'
)

#  find schema dirs containing <schema>/libexec/ssq-$SCHEMA executable

find .								\
	-maxdepth 1						\
	-type d							\
	! -name .						\
	$FIND_OPT_IGNORE						|
  sed 's@\./@@'							|
  while read D;  do
  	if [ -x $D/libexec/ssq-$D ];  then
		echo $D
	fi
  done
STATUS=${PIPESTATUS[*]}
test "$STATUS" = '0 0 0'
