#!/usr/bin/env perl
#
#  Synopsis:
#	Auto-made script /cgi-bin/schema/setcore, made by cgi2perl5.
#  Source Path:
#	setcore.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT}
;

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib/schema", "$ENV{SERVER_ROOT}/lib";

our %CGI;

require 'httpd2.d/common.pl';
$CGI{name} = 'setcore';
#
#  Default content type for all elements.
#
$CGI{GET}->{out}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'input|dl|table|(?:pre[.]hex)|(?:span[.]nav)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='input']
#
$CGI{GET}->{out}->{putter}->{'input'}->{name} = 'input';

#
#  BEGIN: /cgi/GET/out/putter[@name=input]/query-args
#
$CGI{GET}->{out}->{putter}->{'input'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=input]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl']
#
$CGI{GET}->{out}->{putter}->{'dl'}->{name} = 'dl';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{lim} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{offset} = {
	perl5_re	=>	'[+0-9]{1,10}',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=dl]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='table']
#
$CGI{GET}->{out}->{putter}->{'table'}->{name} = 'table';

#
#  BEGIN: /cgi/GET/out/putter[@name=table]/query-args
#
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{lim} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{offset} = {
	perl5_re	=>	'[+0-9]{1,10}',
};
#
#  END: /cgi/GET/out/putter[@name=table]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='table']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='pre.hex']
#
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{name} = 'pre.hex';

#
#  BEGIN: /cgi/GET/out/putter[@name=pre.hex]/query-args
#
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=pre.hex]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='pre.hex']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='span.nav']
#
$CGI{GET}->{out}->{putter}->{'span.nav'}->{name} = 'span.nav';

#
#  BEGIN: /cgi/GET/out/putter[@name=span.nav]/query-args
#
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{offset} = {
	perl5_re	=>	'[+0-9]{1,10}',
};
$CGI{GET}->{out}->{putter}->{'span.nav'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=span.nav]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='span.nav']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
