#!/bin/bash
#
#  Synopsis:
#	Get the exit status of invoking xmllint on blob.
#  Usage:
#	get-xmllint_status <blob udig> <size>
#  Exit Status:
#	0	blob is well formed according to postgres
#	1	blob is not well formed according to postgres
#	2	blob does not exist
#	3	wrong number of arguments
#	4	unknown blobio error
#	5	unknown database error
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	TMPDIR
#
PROG=get-is-pg-well-formed
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.blob

leave()
{
	rm -f $TMP_BLOB
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

test $# = 2 || die 'wrong number of arguments' 3
UDIG=$1
SIZE=$2

blobio get --output-path $TMP_BLOB --udig $UDIG --service $BLOBIO_GET_SERVICE
STATUS=$?

case $STATUS in
0)
	;;
1)
	exit 2
	;;
*)
	die "blobio get $UDIG $TMP_BLOB failed: exit status=$STATUS" 12
	;;
esac

is-pg-well-formed <$TMP_BLOB $SIZE
STATUS=$?
test $STATUS -le 9 && exit $STATUS
die "xmllint --stream --nonet --noout failed: exit status=$STATUS" 13
