#!/bin/bash
#
#  Synopsis:
#	Invoke JSON_checker on a blob
#  Exit Status:
#	0	valid json according to the program JSON_checker
#	1	not valid json according to the program JSON_checker
#	2	blob does not exist
#	3	wrong number of command line arguments
#	4	unknown blobio error
#	5	unknown JSON_checker error
#  Environment
#	BLOBIO_SERVICE
#  Usage:
#	get-JSON_checker <blob> <byte count>
#  Blame:
#  	jmscott@setspace.com
#  	setspace@gmail.com
#
PROG=get-JSON_checker
TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.blob

leave()
{
	rm -f $TMP_BLOB
}

trap leave EXIT

die()
{
	MSG=$1
	STATUS=$2
	echo "JSON_checker.sh: ERROR: $MSG" >&2
	exit $STATUS
}

test $# = 1 || die "wrong number of command line arguments" 3
UDIG=$1

blobio get --udig "$UDIG" --service $BLOBIO_SERVICE --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 2
	;;
*)
	die "blobio get failed: exist status=$STATUS" 4
	;;
esac

#  is the blob true json
JSON_checker <$TMP_BLOB
STATUS=$?
case "$STATUS" in
0|1)
	exit $STATUS
	;;
*)
	die "JSON_checker failed: exit status=$STATUS" 5
	;;
esac
