#!/usr/bin/env bash
#
#  Synopsis:
#	Count blobs in table jsonorg.fault
#  Usage:
#	ssq jsonorg service fault
#
source $SETSPACE_ROOT/lib/ssq-common.bash
USAGE='count'

PSQL=$SSQ_COMMON_PSQL_TSV
SQL=lib/$PROG.sql

$PSQL --file $SQL || die "psql fault count failed: exit status=$?"
