#!/usr/bin/env bash
#
#  Synopsis:
#	Detail listing of blobs
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='<udig> ...'

test $# = 0 && usage

while [ "$1" ];  do
	BLOB="$1";  shift

	frisk_udig "$BLOB"
	ssq jsonorg udig $BLOB || die "ssq jsonorg udig failed: exit status=$?"
done
