#!/usr/bin/env bash
#
#  Synopsis:
#	Backend libexec for schema jsonorg, invoked by script bin/ssq
#
source $SETSPACE_ROOT/lib/ssq-common.bash
USAGE='[service|rummy|fault]'

test $# = 0 && die 'wrong cli count: need > 0'

exec_help $@
exec_udig $@
exec_action $@
