#!/usr/bin/env bash
#
#  Synopsis:
#	List table jsonorg.fault
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='[count]'

PSQL=$SSQ_COMMON_PSQL_TSV
SQL=lib/$PROG.sql

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql fault failed: exit status=$?"
	exit 0
fi
exec_help $@
exec_action $@
