#!/bin/bash
#
#  Synopsis:
#	Concatentate to standard out the blob pages of a pdf blob.
#  Usage:
#	cat-pdf-pages <udig>
#  Exit Status:
#	0	all pages fetched
#	1	blob does not exist
#	2	wrong number of command line arguments
#	3	sql error
#	4	error fetching blob
#	64	unknown error
#  Environment:
#	BLOBIO_GET_SERVICE
#	BLOBIO_SERVICE
#	TMPDIR
#
PROG=$(basename $0)

SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"

TMP_PAGES=${TMPDIR:=/tmp}/$PROG.udig
TMP_ERR=${TMPDIR:=/tmp}/$PROG.err

leave()
{
	rm -f $TMP_PAGES $TMP_ERR
}

trap leave EXIT QUIT INT TERM

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $@" >&1
	exit $STATUS
}

test $# = 1 || die 'wrong number of command line arguments' 2
PDF_UDIG=$1
psql --quiet --no-psqlrc --output=$TMP_PAGES <<END 2>$TMP_ERR

\\pset tuples_only true
\\pset format unaligned

select
	page_blob
  from
  	pdfbox2.extract_page_utf8
  where
  	pdf_blob = '$PDF_UDIG'
  order by
  	page_number asc
END
STATUS=$?

if [ $STATUS -ne 0 ];  then
	test -s $TMP_ERR && cat $TMP_ERR >&2
	die "psql failed: exit status=$STATUS"
fi
while read PAGE_UDIG;  do
	blobio get $SERVICE --udig $PAGE_UDIG ||
		die "blobio get failed: exit status=$?" 4
done <$TMP_PAGES
test $? = 0 || die "unknown error reading blobs: exit status=$?"
