#!/bin/bash
#
#  Synopsis:
#	Merge any stale json pdfbox2 tuples into pdfbox2 tables
#  Usage:
#	PDFBOX2_ROOT=/usr/local/setspace/schema/pdfbox2
#
#	* * * * * sbin/cron-merge-json '-1 Hour' >>log/cron-merge-json.log 2>&1
#

PROG=cron-merge-json

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S' ): $PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

trap leave EXIT
log 'hello, world'

test $# = 1 || die 'wrong number of arguments'
SINCE=$1
log "since: $SINCE"

test -n "$PDFBOX2_ROOT" || die 'environment variable not defined PDFBOX2_ROOT'
log "PDFBOX2_ROOT=$PDFBOX2_ROOT"
cd $PDFBOX2_ROOT || die "cd $PDFBOX2_ROOT failed"
test -e etc/profile || die "missing expected profile: $(pwd)/etc/profile"
log 'sourcing etc/profile ...'
. etc/profile

log 'dumping PG variables ...'
env | grep '^PG' | while read E;  do
	log $E
done

SQL=lib/merge-json-pddocument.sql
log "invoking sql merge script: $SQL"
psql -f $SQL --variable=since="'$SINCE'" ||
			die "psql -f $SQL $SINCE failed: exit status=$?"

SQL=lib/merge-json-extract_utf8.sql
log "invoking sql merge script: $SQL"
psql -f $SQL --variable=since="'$SINCE'" ||
			die "psql -f $SQL $SINCE failed: exit status=$?"
