#!/bin/bash
#
#  Synopsis:
#	Merge any stale json pdfbox2 tuples into pdfbox2 tables
#  Usage:
#	PDFBOX2_ROOT=/
#	* * * * * sbin/cron-merge-json >>cron-merge-json.log '-1 Hour' 2>&1
#

PROG=cron-merge-json
JOB_UDIG=${TMPDIR:=/tmp}/$PROG-job-$$.udig

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S' ): $PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	rm -f $JOB_UDIG
	log 'good bye, cruel world'
}

trap leave EXIT
log 'hello, world'

test $# = 1 || die 'wrong number of arguments'
SINCE=$1
log "syncing since $SINCE"

test -n "$PDFBOX2_ROOT" || die 'environment variable not defined PDFBOX2_ROOT'
log "PDFBOX2_ROOT=$PDFBOX2_ROOT"
cd $PDFBOX2_ROOT || die "cd $PDFBOX2_ROOT failed"
test -e etc/profile || die "missing expected profile: $(pwd)/etc/profile"
log 'sourcing etc/profile ...'
. etc/profile

log 'dumping PG variables ...'
env | grep '^PG' | while read E;  do
	log $E
done

log 'extracting blobs in pdfbox2.pddocument_pending'
psql --var OUT=JOB_UDIG.out --quiet --tuples-only --no-align --no-psqlrc <<END
\\o :OUT
select
	blob
  from 
  	pdfbox2.pddocument_pending
END

SQL=lib/merge-json-pddocument.sql
log "invoking sql merge script: $SQL"
psql -f $SQL --variable=since="'$SINCE'" ||
			die "psql -f $SQL $SINCE failed: exit status=$?"

SQL=lib/merge-json-extract_utf8.sql
log "invoking sql merge script: $SQL"
psql -f $SQL --variable=since="'$SINCE'" ||
			die "psql -f $SQL $SINCE failed: exit status=$?"
