#!/bin/bash
#
#  Synopsis:
#	Extract UTF8 text from proven PDF and store results in json blob.
#  Usage:
#	extract_utf82pg <udig>
#  Exit Status:
#	0	extracted utf8 text and stored json blob
#	1	pdf failed to load
#	2	blob does not exist
#	3	wrong number of arguments
#	4	PDFBOX2_JAR not defined or file does not exist
#	5	blobio error
#	6	json error
#	7	java ExtractText unexpected exit status
#	8	pg database error
#  Java Environment:
#	The jar of pdfbox, version 2, must be in the CLASSPATH.
#  Environment:
#	BLOBIO_ALGORITHM=${BLOBIO_ALGORITHM:=sha}
#	BLOBIO_SERVICE=${BLOBIO_SERVICE:=localhost:1797}
#	PDFBOX2_JAR
#  Note:
#	I have seen extract_utg8_pending inserted but not cleared.
#	May have a race condition.
#

PROG=extract_utf82pg

TMP_BLOB=${TMP_DIR:=/tmp}/$PROG-$$.pdf
TMP_ERR=${TMP_DIR:=/tmp}/$PROG-$$.err
TMP_UTF8=${TMP_DIR:=/tmp}/$PROG-$$.utf8
TMP_JSON=${TMP_DIR:=/tmp}/$PROG-$$.json

leave()
{
	rm -f $TMP_BLOB $TMP_ERR $TMP_UTF8 $TMP_JSON
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

test $# = 1 || die 'wrong number of arguments' 3
UDIG=$1

#  Note: ought to be in CLASSPATH!
test -n "$PDFBOX2_JAR" || die "environment not defined: PDFBOX2_JAR" 4
test -e $PDFBOX2_JAR || die "jar file does not exist: $PDFBOX2_JAR" 4

#  fetch the pdf blob

blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_SERVICE
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 2
	;;
*)
	die 'blobio get failed' 5
	;;
esac

put_file()
{
	FP=$1
	if [ ! -e $FP ];  then
		echo null
		return
	fi

	DIG=$(
		blobio eat					\
			--input-path $FP			\
			--algorithm $BLOBIO_ALGORITHM		\
	)
	test $? = 0 ||  die "blobio eat failed: exit status=$?" 5
	FILE_UDIG=$BLOBIO_ALGORITHM:$DIG
	blobio put --udig $FILE_UDIG --input-path $FP --service $BLOBIO_SERVICE
	test $? = 0 || die "blobio put failed: exit status=$?" 5
	echo '"'$FILE_UDIG'"'
}

#  execute the java extract.

java -jar $PDFBOX2_JAR ExtractText $TMP_BLOB $TMP_UTF8 2>$TMP_ERR
EXIT_STATUS=$?
test $EXIT_STATUS = 0 -o $EXIT_STATUS = 1 ||
		die "java ExtractText failed: exit status=$EXIT_STATUS" 7

UTF8_BLOB=$(put_file $TMP_UTF8)
test $? = 0 || exit 5

STDERR_BLOB=$(put_file $TMP_ERR)
test $? = 0 || exit 5

cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 6
{
	"pdfbox2.setspace.com": {
		"extract_utf8": {
			"blob":		"$UDIG",
			"exit_status":	$EXIT_STATUS,
			"utf8_blob": 	$UTF8_BLOB,
			"stderr_blob":	$STDERR_BLOB
		},
		"date":		"$(date)",
		"hostname":	"$(hostname)",
		"USER":		"$USER",
		"process_id":	$$
	}
}
END

put_file $TMP_JSON >/dev/null 
test $? = 0 || exit 5

#  put the extract_utf8 record to the database
psql --no-psqlrc --quiet <<END || die "psql insert failed: exit status=$?" 8

\\set ON_ERROR_STOP on

INSERT INTO
  pdfbox2.extract_utf8(
  	blob,
	exit_status,
	utf8_blob,
	stderr_blob
    ) VALUES (
    	'$UDIG',
	$EXIT_STATUS,
	$(echo $UTF8_BLOB | tr '"' "'"),
	$(echo $STDERR_BLOB | tr '"' "'")

    ) ON CONFLICT
    	DO NOTHING
;
DELETE FROM pdfbox2.extract_utf8_pending
  WHERE
  	blob = '$UDIG'
;
END

exit $EXIT_STATUS
