#!/bin/bash
#
#  Synopsis:
#	Simple keyword query of PDF blobs and associated titles.
#  Usage:
#	pdfq 'suffix tree ...' | more
#	pdfq 'word1 word2 ...' 100
#	pdfq 'word1 word2 ...' 10 20
#
#	# default limit is 10 and offset is 0
#	pdfq <keywords> [limit [offset]]
#  Exit Status:
#	0	Matching count and tuples written to standard output
#	1	psql internal error (e.g., out of memory)
#	2	bad database connection
#	3	error in sql script with ON_ERROR_STOP set
#	10	wrong command line arguments
#  Environment:
#	PDFBOX2_ROOT
#	PostgreSQL PG* variables
#  Depends:
#	Schema pgtexts
#	$PDFBOX2_ROOT/lib/pdfq-keyword.sql	
#  Note:
#	Eventually rewritten in go or rasql
#
PROG=pdfq
LIMIT=10
OFFSET=0

die()
{
	echo "$PROG: ERROR: $1" >&2
	exit $2
}

test -n "$PDFBOX2_ROOT" || die 'environment not defined: PDFBOX2_ROOT'

case $# in
1)
	KEYWORDS="$1"
	;;
2)
	KEYWORDS="$1"
	LIMIT=$2
	;;
3)
	KEYWORDS="$1"
	LIMIT=$2
	OFFSET=$3
	;;
*)
	die 'wrong number of command line arguments' 10
	;;
esac

psql	--quiet								\
	--no-psqlrc 							\
	--file $PDFBOX2_ROOT/lib/pdfq.sql				\
	--set ts_conf="'english'"					\
	--set keywords="'$KEYWORDS'"					\
	--set limit="$LIMIT" 						\
	--set offset="$OFFSET" 						||
		die "psql failed: exit status=$?" $?
