#!/bin/bash
#
#  Synopsis:
#	Wait for the setspace.byte_count to appear for extracted utf8 blob
#  Usage:
#	wait-utf8-byte_count <max wait> <pdf udig>
#  Exit Status:
#	0	ok, blob appeared
#	1	ok, blob failed to appear after <max wait> seconds.
#	2	utf8 blob does not exist in table extract_text_utf8
#	3	wrong number of arguments
#	4	unexpected sql error
#	5	unexpected error in spin-wait-blob
#  Note:
#	waiting for blobs is a huge kludge, to be replaced with downstream
#	logical replication.
#

die()
{
	echo "wait-utf8-byte_count: ERROR: $1" >&2
	exit $2
}

test $# = 2 || die 'wrong number of arguments' 3

TIMEOUT=$1
PDF_UDIG=$2
UTF8_UDIG=$(
	psql --quiet --tuples-only --no-psqlrc --no-align <<END
select
	utf8_blob
  from
  	pdfbox2.extract_text_utf8
  where
  	blob = '$PDF_UDIG'::udig
END
)
test $? = 0 || die "sql failed: exit status=$?"  4
test -n "$UTF8_UDIG" || exit 2
spin-wait-blob setspace.byte_count blob $TIMEOUT $UTF8_UDIG
STATUS=$?
test $STATUS -lt 2 && exit $STATUS 
die "spin-wait-blob failed: exit status=$?" 5
