#!/bin/bash
#
#  Synopsis:
#	On a valid gzip blob, put gzip --list --verbose into table.
#  Usage:
#	BLOB=bc160:d28d2591211cc730896549a75167acd00b6159d8
#	merge-gunzip_list_verbose $BLOB
#

TMP_BLOB=${TMPDIR:=/tmp}/$(basename $0).$$
trap "rm -f $TMP_BLOB" EXIT TERM

die()
{
	STATUS=$1
	shift
	echo "ERROR: $@" >&2
	exit $STATUS
}

test $# = 1 || die 2 "wrong argument count: got $#, expected 1"
BLOB=$1

test -n "$BLOBIO_SERVICE" || die 2 'env not defined: BLOBIO_SERVICE'

#  Does the blob exist?

blobio get --udig $BLOB --service $BLOBIO_SERVICE --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
        ;;
1)
        die 1 "eat: blob does not exist: $BLOB"
        ;;
*)
        die 2 "blobio eat failed: exit status=$STATUS"
        ;;
esac

#  we assume the blob
gunzip --list --verbose --name $TMP_BLOB | (
	read LINE
	case "$LINE" in
	method*)
		;;
	*)
		die 2 "gunzip list/verbose failed: $LINE"
		;;
	esac
	IFS=' ' read -r METHOD CRC
	echo $METHOD $CRC
)
