#!/bin/bash
#
#  Synopsis:
#	Run 'file --brief' on blob and write tuple to postgresql.
#  Usage:
#	merge-file <blob udig>
#  Exit Status:
#	0	ok
#	1	blob does not exist
#	2	file output is not utf8
#	3	wrong number of command line arguments
#	4	blobio get failed
#	5	command 'file --brief <blob> failed'
#	6	sql merge failed
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	TMPDIR
#  Note:
#	Add option flag -E to force exit on first error.  For some reason posix
#	specifically says not abort upon error.  wierd.
#

PROG=merge-file
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.blob.$$
TMP_FILE=${TMPDIR:=/tmp}/$PROG.file.$$

leave()
{
	rm -f $TMP_BLOB $TMP_FILE
}
trap leave EXIT
trap '' PIPE
test $# = 1 || die 'wrong number of arguments' 3
FILE_BLOB=$1

#  fetch the blob into temporary file

blobio get --udig $FILE_BLOB --service $BLOBIO_GET_SERVICE --output-path $TMP_BLOB
STATUS=$?
test $STATUS = 1 && exit 1
test $STATUS = 0 || die "blobio get failed: exit status=$STATUS" 4

#  call 'file --brief' and save output to temp file

file --brief $TMP_BLOB >$TMP_FILE
test $? = 0 || die "file command failed: exit status=$?" 5

#  insure file output is proper utf8

is-utf8wf <$TMP_FILE
STATUS=$?

#  null file type indicates non-utf8 in file type string

case $STATUS in
0)
	IS_NULL=no
	EXIT_STATUS=0
	;;
1|2)
	IS_NULL=yes
	EXIT_STATUS=2
	;;
*)
	die "is-utf8wf failed: exit status=$STATUS" 5
	;;
esac

if [ $IS_NULL = no ];  then

	#  stat the size of the temp file with utf8
	FILE_TYPE_SIZE=$(file-stat-size $TMP_FILE)
	test $? = 0 || die "file-stat-size failed: exit status=$?" 5

	#  merge the output of file command into table fffile5.file
	merge-stdin-file <$TMP_FILE $FILE_BLOB $FILE_TYPE_SIZE ||
				die "merge-stdin-file failed: exit status=$?" 6
else
	psql --quiet --no-psqlrc <<END
INSERT INTO fffile5.file(
	blob,
	file_type
  ) VALUES(
  	'$FILE_BLOB',
	null
  )  ON CONFLICT
  	DO NOTHING
;
END
	test $? = 0 || die "psql null insert failed: exit status=$?" 6
fi

exit $EXIT_STATUS
