#!/usr/bin/env bash
#
#  Synopsis:
#	List blobs in fault in schema fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

SQL="lib/$PROG.sql"

PSQL='psql
       --expanded
       --tuples-only
       --set=ON_ERROR_STOP=1
       --no-psqlrc
       --no-readline
'

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql fault ls failed: exit status=$?"
	exit 0
fi

exec_udig $@

die "unknown action: $1"
