#!/usr/bin/env bash
#
#  Synopsis:
#	Count blobs in fault in schema fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE=''

SQL="lib/$PROG.sql"

PSQL=$SSQ_COMMON_PSQL_TSV

$PSQL --file $SQL || die "psql fault count failed: exit status=$?"
