#!/usr/bin/env bash
#
#  Synopsis:
#	script to invoke libexec/ssq-fffile5-ls-* scripts
#  Exit Status:
#	0	query ok, blob may of may not exists
#
PROG=$(basename $0)
SQL=lib/$PROG.sql
PSQL='psql
	--expanded
	--pset null=Unknown
	--tuples-only
'

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# = 1 || die "wrong count of cli args: got $#, want 1"

BLOB=$1
shift

#
#  Note:
#	How do we know perl regex always enabled?
#
[[ $BLOB =~ ^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$ ]]			||
				die "not a udig: $BLOB"
	
$PSQL --set blob=$BLOB --file $SQL || die "psql ls failed: exit stats=$?"

exit 0
