#!/usr/bin/env bash
#
#  Synopsis:
#	Count blobs in table fffile5.blob
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE=

SQL="lib/$PROG.sql"
PSQL=$SSQ_COMMON_PSQL_TSV

$PSQL --file $SQL || die "psql blob count failed: exit status=$?"
