#!/usr/bin/env bash
#
#  Synopsis:
#	script to invoke libexec/ssq-fffile5-* scripts
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='[blob|fault|service|rummy] ...'

test $# = 0 && usage

exec_udig "$1"
exec_action $@
