#!/usr/bin/env bash
#
#  Synopsis:
#	Count blobs in table fffile5.blob
#
source $SETSPACE_ROOT/lib/ssq-common.bash

SQL="lib/$PROG.sql"
PSQL=$SSQ_COMMON_PSQL

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

$PSQL --file $SQL || die "psql blob count failed: exit status=$?"
