#!/usr/bin/env bash
#
#  Synopsis:
#	query fffile5 schema for blobs in rummy
#  Usage:
#	called by script in libexec/ssq-fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='[count]'
SQL="lib/$PROG.sql"

PSQL=$SSQ_COMMON_PSQL_TSV

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql rummy failed: exit status=$?"
	exit 0
fi

exec_help $@
exec_action $@
