#!/usr/bin/env bash
#
#  Synopsis:
#	script to invoke libexec/ssq-fffile5-* scripts
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='[blob|fault|service|rummy] | <udig> ...'

test $# = 0 && usage

exec_help $@
exec_udig $@
exec_action $@
