#!/usr/bin/env bash
#
#  Synopsis:
#	Count blobs in service in schema fffile5
#  Usage:
#  Note:
#	Think about adding "Is Rummy".  Does being a rummy imply nt in service?
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE=''
SQL="lib/$PROG.sql"

PSQL=$SSQ_COMMON_PSQL_TSV

$PSQL --file $SQL || die "psql service count failed: exit status=$?"

exit 0
