#!/usr/bin/env bash
#
#  Synopsis:
#	List blobs in table fffile5.fault
#  Usage:
#	called by script in libexec/ssq-fffile
#
USAGE='[count]'
source $SETSPACE_ROOT/lib/ssq-common.bash

PSQL=$SSQ_COMMON_PSQL_TSV
SQL="lib/$PROG.sql"

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql fault failed: exit status=$?"
	exit 0
fi

exec_action $@
