#!/usr/bin/env bash
#
#  Synopsis:
#	List blobs in fault in schema fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='<udig> ...'

test $# -gt 0 || die 'bad cli arg count: got 0, want > 0'

while [ "$1" ];  do
	BLOB="$1";  shift

	frisk_udig "$BLOB"
	ssq fffile5 fault udig $BLOB					||
			die "ssq fffile5 fault udig failed: exit status=$?"
done
