#!/usr/bin/env bash
#
#  Synopsis:
#	list recent blobs in setcore which may not be in service
#
PROG=$(basename $0)

PSQL='psql
	--set=ON_ERROR_STOP=1
	--no-psqlrc
	--no-readline
	--expanded
'

help()
{
	echo "usage: $PROG"
}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# = 0 || die "wrong number of cli arg: got $#, want 1"

$PSQL <<END || die "psql recent failed: exit status=$?"
SELECT
	f.blob AS "Blob",
	f.file_type AS "File Type",
	mt.mime_type AS "Mime Type",
	mt.mime_encoding AS "Mime Encoding",
	CASE
	  WHEN srv.blob IS NULL THEN
	  	'No'
	  ELSE
	  	'Yes'
	END AS "Service?"
	CASE
	  WHEN rum.blob IS NULL THEN
	  	'No'
	  ELSE
	  	'Yes'
	END AS "Rummy?",'
	s.discover_time AS "Discover Time"
  FROM
  	fffile5 f
	  JOIN setcore.service srv ON (src.blob = f.blob)
	  LEFT OUTER JOIN fffile5.file_mime_type mt ON (mt.blob = f.blob)
	  LEFT OUTER JOIN fffile5.file_mime_encoding me ON (me.blob = f.blob)
	  LEFT OUTER JOIN file.service srv ON (srv.blob = f.blob)
	  LEFT OUTER JOIN file.rummy rum ON (rum.blob = f.blob)
  ORDER BY
  	s.discover_time DESC
  LIMIT
  	10
END
