#!/usr/bin/env bash
#
#  Synopsis:
#	script to invoke libexec/ssq-fffile5-ls-* scripts
#
PROG=$(basename $0)

help()
{
	echo "usage: $PROG ls <udig>"
}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# -ge 1 || die "wrong cli arg count: $#, want > 1"

ACTION=$1; shift

LIBEXEC=libexec/ssq-fffile5-$ACTION
test -x $LIBEXEC || die "no libexec for action: $ACTION"

exec $LIBEXEC $@
