#!/usr/bin/env bash
#
#  Synopsis:
#	query fffile5 schema for blobs in service
#  Usage:
#	called by script in libexec/ssq-fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE="[count]"

PSQL=$SSQ_COMMON_PSQL_TSV
SQL=lib/$PROG.sql

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql service failed: exit status=$?"
	exit 0
fi

exec_help $@
exec_udig $@
exec_action $@
