#!/usr/bin/env bash
#
#  Synopsis:
#	list blobs in table fffile5.blob
#  Usage:
#	called by script in libexec/ssq-fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

PSQL=$SSQ_COMMON_PSQL
SQL=lib/$PROG.sql

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql failed: exit status=$?"
	exit 0
fi

exec_action $@
