#!/usr/bin/env bash
#
#  Synopsis:
#	list details for fffile5 for a particular blob
#  Usage:
#	ssq fffile5 ls <udig>
#  Note:
#	Add duration to discover time
#
PROG=$(basename $0)
SQL=lib/$PROG.sql

PSQL='psql
	--expanded
	--pset null=Unknown
	--tuples-only
	--no-psqlrc
	--pset format=wrapped
	--pset footer=off
'

help()
{
	echo "usage: $PROG"
}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# = 1 || die "cli arg count wrong: got $#, want 1"
BLOB=$1

#
#  Note:
#	How do we know perl regex always enabled?
#
[[ $BLOB =~ ^[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}$ ]]			||
					die "not a udig: $BLOB"
$PSQL --set blob=$BLOB --file $SQL || die "psql ls blob failed: exit status=$?"

exit 0
