#!/usr/bin/env bash
#
#  Synopsis:
#	List blobs in fault in schema fffile5
#
source $SETSPACE_ROOT/lib/ssq-common.bash

PSQL='psql
       --expanded
       --tuples-only
       --set=ON_ERROR_STOP=1
       --no-psqlrc
       --no-readline
       --quiet
'

SQL="lib/$PROG.sql"

test $# = 1 || die "cli arg count wrong: got $#, want 1"
BLOB=$1;  shift
is_udig $BLOB || die "arg not udig: $BLOB"
$PSQL --set blob=$BLOB --file $SQL					||
		die "psql fault ls blob failed: exit status=$?"
