#!/usr/bin/perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/account.
#  Source Path:
#	account.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	/cgi-bin/account was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'account';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'(?:div[.]err)|logout|(?:a[.]ll)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='div.err']
#
$CGI{GET}->{out}->{putter}->{'div.err'}->{name} = 'div.err';
$CGI{GET}->{out}->{putter}->{'div.err'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=div.err]/query-args
#
$CGI{GET}->{out}->{putter}->{'div.err'}->{'query-args'}->{arg}->{err} = {
	perl5_re	=>	'.{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=div.err]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='div.err']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='logout']
#
$CGI{GET}->{out}->{putter}->{'logout'}->{name} = 'logout';

#
#  BEGIN: /cgi/GET/out/putter[@name=logout]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='logout']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='a.ll']
#
$CGI{GET}->{out}->{putter}->{'a.ll'}->{name} = 'a.ll';
$CGI{GET}->{out}->{putter}->{'a.ll'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=a.ll]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='a.ll']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='post.dump']
#
$CGI{POST}->{in}->{putter}->{'post.dump'}->{name} = 'post.dump';
#
#  END: /cgi/POST/in/putter[@name='post.dump']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='new']
#
$CGI{POST}->{in}->{putter}->{'new'}->{name} = 'new';
$CGI{POST}->{in}->{putter}->{'new'}->{vars}->{var}->{role} = {
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'new'}->{vars}->{var}->{passwd} = {
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'new'}->{vars}->{var}->{passwdv} = {
	required	=>	'yes',
};
#
#  END: /cgi/POST/in/putter[@name=new]/vars
#

#
#  END: /cgi/POST/in/putter[@name='new']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='login']
#
$CGI{POST}->{in}->{putter}->{'login'}->{name} = 'login';
$CGI{POST}->{in}->{putter}->{'login'}->{vars}->{var}->{role} = {
	required	=>	'yes',
};
$CGI{POST}->{in}->{putter}->{'login'}->{vars}->{var}->{passwd} = {
	required	=>	'yes',
};
#
#  END: /cgi/POST/in/putter[@name=login]/vars
#

#
#  END: /cgi/POST/in/putter[@name='login']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='logout']
#
$CGI{POST}->{in}->{putter}->{'logout'}->{name} = 'logout';
#
#  END: /cgi/POST/in/putter[@name='logout']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
