#!/usr/bin/perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/blob.
#  Source Path:
#	blob.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	/cgi-bin/blob was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'blob';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'input|title|(?:div[.]nav)|dl|(?:select[.]oby)|(?:pre[.]hex)|(?:pre[.]hex)|(?:dl[.]detail)|mime|a|(?:a[.]hex)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='input']
#
$CGI{GET}->{out}->{putter}->{'input'}->{name} = 'input';
$CGI{GET}->{out}->{putter}->{'input'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=input]/query-args
#
$CGI{GET}->{out}->{putter}->{'input'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=input]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='title']
#
$CGI{GET}->{out}->{putter}->{'title'}->{name} = 'title';
$CGI{GET}->{out}->{putter}->{'title'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=title]/query-args
#
$CGI{GET}->{out}->{putter}->{'title'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=title]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='title']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='div.nav']
#
$CGI{GET}->{out}->{putter}->{'div.nav'}->{name} = 'div.nav';
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=div.nav]/query-args
#
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'\d{1,10}',
	default	=>	'20',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'[1-9]\d{0,9}',
	default	=>	'1',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{mime} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=div.nav]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='div.nav']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl']
#
$CGI{GET}->{out}->{putter}->{'dl'}->{name} = 'dl';
$CGI{GET}->{out}->{putter}->{'dl'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'\d{1,10}',
	default	=>	'20',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'[1-9]\d{0,9}',
	default	=>	'1',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{oby} = {
	perl5_re	=>	'rand|dtime|adtim|bcnta|bcntd',
	default	=>	'dtime',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{mime} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=dl]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='select.oby']
#
$CGI{GET}->{out}->{putter}->{'select.oby'}->{name} = 'select.oby';
$CGI{GET}->{out}->{putter}->{'select.oby'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select.oby]/query-args
#
$CGI{GET}->{out}->{putter}->{'select.oby'}->{'query-args'}->{arg}->{oby} = {
	perl5_re	=>	'rand|dtime|adtim|bcnta|bcntd',
	default	=>	'dtime',
};
#
#  END: /cgi/GET/out/putter[@name=select.oby]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select.oby']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='pre.hex']
#
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{name} = 'pre.hex';
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=pre.hex]/query-args
#
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=pre.hex]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='pre.hex']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='pre.hex']
#
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{name} = 'pre.hex';
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=pre.hex]/query-args
#
$CGI{GET}->{out}->{putter}->{'pre.hex'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=pre.hex]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='pre.hex']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl.detail']
#
$CGI{GET}->{out}->{putter}->{'dl.detail'}->{name} = 'dl.detail';
$CGI{GET}->{out}->{putter}->{'dl.detail'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl.detail]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl.detail'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=dl.detail]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl.detail']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='mime']
#
$CGI{GET}->{out}->{putter}->{'mime'}->{name} = 'mime';

#
#  BEGIN: /cgi/GET/out/putter[@name=mime]/query-args
#
$CGI{GET}->{out}->{putter}->{'mime'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=mime]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='mime']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='a']
#
$CGI{GET}->{out}->{putter}->{'a'}->{name} = 'a';
$CGI{GET}->{out}->{putter}->{'a'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=a]/query-args
#
$CGI{GET}->{out}->{putter}->{'a'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
$CGI{GET}->{out}->{putter}->{'a'}->{'query-args'}->{arg}->{text} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=a]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='a']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='a.hex']
#
$CGI{GET}->{out}->{putter}->{'a.hex'}->{name} = 'a.hex';
$CGI{GET}->{out}->{putter}->{'a.hex'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=a.hex]/query-args
#
$CGI{GET}->{out}->{putter}->{'a.hex'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[[:alnum:]]{1,15}:[[:graph:]]{1,255}',
};
$CGI{GET}->{out}->{putter}->{'a.hex'}->{'query-args'}->{arg}->{text} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=a.hex]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='a.hex']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
