#!/usr/bin/perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/pdf.
#  Note:
#	/cgi-bin/pdf was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'pdf';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'input|(?:select[.]oby)|(?:select[.]rppg)|dl|blob|(?:div[.]nav)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='input']
#
$CGI{GET}->{out}->{putter}->{'input'}->{name} = 'input';
$CGI{GET}->{out}->{putter}->{'input'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=input]/query-args
#
$CGI{GET}->{out}->{putter}->{'input'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
#
#  END: /cgi/GET/out/putter[@name=input]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='select.oby']
#
$CGI{GET}->{out}->{putter}->{'select.oby'}->{name} = 'select.oby';
$CGI{GET}->{out}->{putter}->{'select.oby'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select.oby]/query-args
#
$CGI{GET}->{out}->{putter}->{'select.oby'}->{'query-args'}->{arg}->{oby} = {
	perl5_re	=>	'tscd|dtimd|dtima|pgcoa|pgcod|rand',
};
#
#  END: /cgi/GET/out/putter[@name=select.oby]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select.oby']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='select.rppg']
#
$CGI{GET}->{out}->{putter}->{'select.rppg'}->{name} = 'select.rppg';
$CGI{GET}->{out}->{putter}->{'select.rppg'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select.rppg]/query-args
#
$CGI{GET}->{out}->{putter}->{'select.rppg'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'10|20|100|1000|10000',
};
#
#  END: /cgi/GET/out/putter[@name=select.rppg]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select.rppg']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl']
#
$CGI{GET}->{out}->{putter}->{'dl'}->{name} = 'dl';
$CGI{GET}->{out}->{putter}->{'dl'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'\d{1,10}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'[1-9]\d{0,9}',
	default	=>	'1',
};
$CGI{GET}->{out}->{putter}->{'dl'}->{'query-args'}->{arg}->{oby} = {
	perl5_re	=>	'tscd|dtimd|dtima|pgcoa|pgcod|rand',
	default	=>	'tscd',
};
#
#  END: /cgi/GET/out/putter[@name=dl]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='blob']
#
$CGI{GET}->{out}->{putter}->{'blob'}->{name} = 'blob';

#
#  BEGIN: /cgi/GET/out/putter[@name=blob]/query-args
#
$CGI{GET}->{out}->{putter}->{'blob'}->{'query-args'}->{arg}->{udig} = {
	perl5_re	=>	'[^:]{1,15}:[^:]{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=blob]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='blob']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='div.nav']
#
$CGI{GET}->{out}->{putter}->{'div.nav'}->{name} = 'div.nav';
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=div.nav]/query-args
#
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{0,255}',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'\d{1,10}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'[1-9]\d{0,9}',
	default	=>	'1',
};
$CGI{GET}->{out}->{putter}->{'div.nav'}->{'query-args'}->{arg}->{oby} = {
	perl5_re	=>	'tscd|dtimd|dtima|pgcoa|pgcod|rand',
	default	=>	'tscd',
};
#
#  END: /cgi/GET/out/putter[@name=div.nav]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='div.nav']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
