<?xml version="1.0" encoding="UTF-8"?>
<cgi name="pdf">
 <title>/cgi-bin/pdf</title>
 <synopsis>HTTP CGI Script /cgi-bin/pdf</synopsis>
 <subversion id="$Id$" />
 <blame>jmscott</blame>
 <GET>
  <examples>
   <example
   	query="/cgi-bin/pdf?help"
   >
    Generate a This Help Page for the CGI Script /cgi-bin/pdf
   </example>
  </examples>
  <out>
   <putter
   	name="input"
	content-type="text/html"
   >
    <query-args>
     <arg
    	name="q"
	perl5_re=".{0,255}"
     />
    </query-args>
   </putter>

   <putter
   	name="select.oby"
	content-type="text/html"
   >
    <query-args>
     <arg
     	name="oby"
	perl5_re="tscd|dtimd|dtima|pgcoa|pgcod|rand"
     />
    </query-args>
   </putter>

   <putter
   	name="select.rppg"
	content-type="text/html"
   >
    <query-args>
     <arg
     	name="rppg"
	perl5_re="10|20|100|1000|10000"
     />
    </query-args>
   </putter>

   <putter
   	name="dl"
	content-type="text/html"
   >
    <query-args>
     <arg
    	name="q"
	perl5_re=".{0,255}"
     />
     <arg
    	name="rppg"
	default="10"
	perl5_re="\d{1,10}"
     />
     <arg
    	name="page"
	default="1"
	perl5_re="[1-9]\d{0,9}"
     />
     <arg
     	name="oby"
	perl5_re="tscd|dtimd|dtima|pgcoa|pgcod|rand"
	default="tscd"
     />
    </query-args>
   </putter>

   <putter
   	name="blob"
   >
    <query-args>
     <arg
    	name="udig"
	perl5_re="[^:]{1,15}:[^:]{1,255}"
     />
    </query-args>
   </putter>

   <putter
   	name="div.nav"
	content-type="text/html"
   >
    <query-args>
     <arg
    	name="q"
	perl5_re=".{0,255}"
     />
     <arg
    	name="rppg"
	default="10"
	perl5_re="\d{1,10}"
     />
     <arg
    	name="page"
	default="1"
	perl5_re="[1-9]\d{0,9}"
     />
     <arg
     	name="oby"
	perl5_re="tscd|dtimd|dtima|pgcoa|pgcod|rand"
	default="tscd"
     />
    </query-args>
   </putter>

  </out>
 </GET>
</cgi>
