#!/usr/bin/perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/property.
#  Source Path:
#	property.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	/cgi-bin/property was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'property';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'table|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='table']
#
$CGI{GET}->{out}->{putter}->{'table'}->{name} = 'table';
$CGI{GET}->{out}->{putter}->{'table'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=table]/query-args
#
$CGI{GET}->{out}->{putter}->{'table'}->{'query-args'}->{arg}->{start} = {
	perl5_re	=>	'[\w]{1,15}',
	default	=>	'today',
};
#
#  END: /cgi/GET/out/putter[@name=table]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='table']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
