#!/usr/bin/perl
#
#  Synopsis:
#	Implements argument processing for /cgi-bin/sengine.
#  Source Path:
#	sengine.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	/cgi-bin/sengine was generated automatically by cgi2perl5.
#
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT};

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib";

our (%CGI);

require 'httpd2.d/common.pl';
$CGI{name} = 'sengine';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'select|input|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='select']
#
$CGI{GET}->{out}->{putter}->{'select'}->{name} = 'select';
$CGI{GET}->{out}->{putter}->{'select'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select]/query-args
#
$CGI{GET}->{out}->{putter}->{'select'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{1,255}',
};
$CGI{GET}->{out}->{putter}->{'select'}->{'query-args'}->{arg}->{eng} = {
	perl5_re	=>	'\w{1,32}',
};
$CGI{GET}->{out}->{putter}->{'select'}->{'query-args'}->{arg}->{page} = {
	perl5_re	=>	'\w{1,32}',
	default	=>	'setspace',
};
$CGI{GET}->{out}->{putter}->{'select'}->{'query-args'}->{arg}->{rppg} = {
	perl5_re	=>	'10|20|100|1000|10000',
	default	=>	'20',
};
#
#  END: /cgi/GET/out/putter[@name=select]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='input']
#
$CGI{GET}->{out}->{putter}->{'input'}->{name} = 'input';
$CGI{GET}->{out}->{putter}->{'input'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=input]/query-args
#
$CGI{GET}->{out}->{putter}->{'input'}->{'query-args'}->{arg}->{q} = {
	perl5_re	=>	'.{1,255}',
};
#
#  END: /cgi/GET/out/putter[@name=input]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='input']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='rd']
#
$CGI{POST}->{in}->{putter}->{'rd'}->{name} = 'rd';
$CGI{POST}->{in}->{putter}->{'rd'}->{vars}->{var}->{q} = {
	perl5_re	=>	'.{1,255}',
};
$CGI{POST}->{in}->{putter}->{'rd'}->{vars}->{var}->{eng} = {
	perl5_re	=>	'\w{1,32}',
};
$CGI{POST}->{in}->{putter}->{'rd'}->{vars}->{var}->{rppg} = {
	perl5_re	=>	'10|20|100|1000|10000',
};
$CGI{POST}->{in}->{putter}->{'rd'}->{vars}->{var}->{page} = {
	perl5_re	=>	'\d{1,10}',
};
$CGI{POST}->{in}->{putter}->{'rd'}->{vars}->{var}->{oby} = {
	perl5_re	=>	'tscd|dtimd|dtima|pgcoa|pgcod|rand',
};
#
#  END: /cgi/POST/in/putter[@name=rd]/vars
#

#
#  END: /cgi/POST/in/putter[@name='rd']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
