#!/bin/bash
#
#  Synopsis:
#	Merge a pending UTF8 blob into table pgtexts.tsv_utf8.
#  Usage:
#	 merge-tsv_utf8 <ts_config> <udig> <blob_size>
#  Arguments:
#	1	text search configuration name
#   	2	udig of the blob
#   	3	size of the blob in bytes
#  Exit Status:
#   	0	ok, tuple was merged
#	1	blob does not exist
#   	2	wrong number of arguments
#	3	unexpected blobio error
#	4	unexpected merge error
#  See:
#	PostgreSQL table pgtexts.tsv_utf8_pending.
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#  
PROG=merge-tsv_utf8
SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

leave()
{
	rm -f $TMP_BLOB
}

trap leave EXIT

test $# = 3 || die 'wrong number of arguments' 2

TS_CONF=$1
UDIG=$2
SIZE=$3

blobio get --udig $UDIG --output-path $TMP_BLOB $SERVICE
STATUS=$?

case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS" 3
	;;
esac
merge-stdin-tsv_utf8 $UDIG $TS_CONF $SIZE <$TMP_BLOB ||
			die "merge-stdin-tsv_utf8 failed: exit status=$?" 4
