#!/bin/bash
#
#  Synopsis:
#	Merge a pending UTF8 blob into table pgtexts.text_utf8.
#  Usage:
#	 merge-text_utf8 <udig> <blob_size>
#  Arguments:
#	1	text search configuration name
#   	2	udig of the blob
#   	3	size of the blob in bytes
#  Exit Status:
#   	0	ok, tuple was merged
#	1	blob does not exist
#   	2	wrong number of arguments
#	3	unexpected blobio error
#	4	unexpected merge error
#  See:
#	PostgreSQL table pgtexts.text_utf8_pending.
#  Environment:
#	BLOBIO_RO_SERVICE
#  
PROG=merge-text_utf8
TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

leave()
{
	rm -f $TMP_BLOB
}

trap leave EXIT

test $# = 2 || die 'wrong number of arguments' 2

UDIG=$1
SIZE=$2

blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_RO_SERVICE
STATUS=$?

case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS" 3
	;;
esac
merge-stdin-text_utf8 $UDIG $SIZE <$TMP_BLOB ||
			die "merge-stdin-text_utf8 failed: exit status=$?" 4
