#!/bin/bash
#
#  Synopsis:
#	curl the arxiv.org rest api for details on particular list of ids..
#  Usage:
#	curl-arxiv-id_list 1612.03343v1
#
URL=http://export.arxiv.org/api/query?id_list=
ID_RE1='[0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9].v[0-9]'
ID_RE2='[0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9][0-9].v[0-9]'

die()
{
	echo "ERROR: $@" >&2
	exit 1
}

test $# = 1 || die 'wrong number of arguments'

ID_LIST="$1"

case "$ID_LIST" in
arvix:|arXiv:)
	die "arxiv prefix not required: $ID_LIST"
	;;
*,*)
	die "only single id allowed in list: $ID_LIST"
	;;
$ID_RE1|$ID_RE2)
	;;
esac

curl "${URL}$ID_LIST" || die "curl arxiv.org failed: exit status=$?"
