#!/bin/bash
#
#  Synopsis:
#	Is a blob well formed xml, according to the expat2 is_xmlwf program?
#  Usage:
#	get-is_xmlwf <blob udig>
#  Exit Status:
#	0	yes, is valid xml
#	1	no, is not valid xml
#	2	blob does not exist from $BLOBIO_GET_SERVICE
#	3	wrong number of arguments
#	4	unexpected 'blobio get' error
#	5	unexpected xmlwf error
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#
PROG=get-is_xmlwf
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.blob

#  bonedheaded xmlwf does NOT set exit code.
#  we must test for size of error output file.
#  ughh.
TMP_XMLWF=${TMPDIR:=/tmp}/$PROG-$$.wf

leave()
{
	rm -f $TMP_BLOB $TMP_XMLWF
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

test $# = 1 || die 'wrong number of arguments' 3

UDIG=$1
blobio get --output-path $TMP_BLOB --udig $UDIG --service $BLOBIO_GET_SERVICE
STATUS=$?

case $STATUS in
0)
	;;
1)
	exit 2
	;;
*)
	die "blobio get $UDIG $TMP_BLOB failed: exit status=$STATUS" 4
	;;
esac

#  non zero exit code means wierdness, not xml validity  
xmlwf $TMP_BLOB >$TMP_XMLWF
test $? = 0 || die "xmlwf failed >$TMP_XMLWF: exit status = $?" 5
test -s $TMP_XMLWF || exit 0
exit 1
