#!/bin/bash
#
#  Synopsis:
#	Is a blob well formed xml, according to the expat2 xmlwf program?
#  Usage:
#	merge-xmlwf_utf8 <blob udig>
#  Exit Status:
#	0	yes, is valid xml
#	1	no, is not valid xml
#	2	blob does not exist from $BLOBIO_GET_SERVICE
#	3	unexpected error
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG{HOST,PORT,USER,PASSWORD,DATABASE}
#
PROG=merge-xmlwf_utf8
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.blob
TMP_XMLWF=${TMPDIR:=/tmp}/$PROG-$$.wf

leave()
{
	rm -f $TMP_BLOB $TMP_XMLWF
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

test $# = 1 || die 'wrong number of arguments' 3

UDIG=$1
blobio get --output-path $TMP_BLOB --udig $UDIG --service $BLOBIO_GET_SERVICE
STATUS=$?

case $STATUS in
0)
	;;
1)
	exit 2
	;;
*)
	die "blobio get $UDIG $TMP_BLOB failed: exit status=$STATUS" 3
	;;
esac

xmlwf $TMP_BLOB >$TMP_XMLWF
STATUS=$?

#
#  Sadly, xmlwf broke the version2 api.  seems to have occured around
#  version v2.4.  Previous 2 versions of xmlwf only returned 0, regardless of
#  the parsability of the xml file.  around v2.4, the exit status suddenly
#  indicated the parsability of the xml file, hence the new table
#
#	expat2.xmlwf_utf8_exit_status
#
#  may god bless semantic versioning.  however, we must never forget that
#  the journey is both long and hard to a true engineering discipline of
#  software.  until such time arrives, i (jsmscott) shall insist on calling
#  programmers computer scientists.
#
merge-stdin-xmlwf_utf8							\
	$UDIG								\
	$(file-stat-size $TMP_XMLWF) 					\
	$STATUS	< $TMP_XMLWF						||
		die "merge-stdin-xmlwf_utf8 failed: exit status=$?" 3
