#!/usr/bin/env perl
#
#  Synopsis:
#	Auto-made script /cgi-bin/schema/fffile5, made by cgi2perl5.
#  Source Path:
#	fffile5.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT}
;

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib/schema", "$ENV{SERVER_ROOT}/lib";

our %CGI;

require 'httpd2.d/common.pl';
$CGI{name} = 'fffile5';
#
#  Default content type for all elements.
#
$CGI{GET}->{out}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'select|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='select']
#
$CGI{GET}->{out}->{putter}->{'select'}->{name} = 'select';

#
#  BEGIN: /cgi/GET/out/putter[@name=select]/query-args
#
#
#  END: /cgi/GET/out/putter[@name='select']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
