#!/usr/bin/env perl
#
#  Synopsis:
#	Auto-made script /cgi-bin/schema/fffile5, made by cgi2perl5.
#  Source Path:
#	fffile5.cgi
#  Source SHA1 Digest:
#	No SHA1 Calculated
#  Note:
#	Do not make changes directly to this script.
#
die "SERVER_ROOT environment variable not defined"
				unless defined $ENV{SERVER_ROOT}
;

#
#  Prepend the $SERVER_ROOT/lib directory
#  to the load path.
#
unshift @INC, "$ENV{SERVER_ROOT}/lib/schema", "$ENV{SERVER_ROOT}/lib";

our %CGI;

#  Note:  ought to be "require jmscott/httpd2.d/common.pl" !
require 'httpd2.d/common.pl';
$CGI{name} = 'fffile5';

#
#  BEGIN: /cgi/GET/out/query-args
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{id} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
$CGI{GET}->{out}->{'query-args'}->{arg}->{class} = {
	perl5_re	=>	'\w[\w-]{0,32}'
};
#
#  'out' query argument must match one of the out putter names.
#
$CGI{GET}->{out}->{'query-args'}->{arg}->{out} = {
	perl5_re	=> 	'(?:span[.]nav[.]mt)|(?:select[.]mt)|(?:mime[.]mt)|(?:dl[.]mt)|help',
	default		=>	'help',
};
#
#  BEGIN: /cgi/GET/out/putter[@name='span.nav.mt']
#
$CGI{GET}->{out}->{putter}->{'span.nav.mt'}->{name} = 'span.nav.mt';
$CGI{GET}->{out}->{putter}->{'span.nav.mt'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=span.nav.mt]/query-args
#
$CGI{GET}->{out}->{putter}->{'span.nav.mt'}->{'query-args'}->{arg}->{mt} = {
	perl5_re	=>	'.*',
	required	=>	'no',
};
$CGI{GET}->{out}->{putter}->{'span.nav.mt'}->{'query-args'}->{arg}->{lim} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'span.nav.mt'}->{'query-args'}->{arg}->{off} = {
	perl5_re	=>	'[+0-9]{1,10}',
	default	=>	'0',
};
#
#  END: /cgi/GET/out/putter[@name=span.nav.mt]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='span.nav.mt']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='select.mt']
#
$CGI{GET}->{out}->{putter}->{'select.mt'}->{name} = 'select.mt';
$CGI{GET}->{out}->{putter}->{'select.mt'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=select.mt]/query-args
#
$CGI{GET}->{out}->{putter}->{'select.mt'}->{'query-args'}->{arg}->{mt} = {
	perl5_re	=>	'.*',
	required	=>	'no',
};
#
#  END: /cgi/GET/out/putter[@name=select.mt]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='select.mt']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='mime.mt']
#
$CGI{GET}->{out}->{putter}->{'mime.mt'}->{name} = 'mime.mt';

#
#  BEGIN: /cgi/GET/out/putter[@name=mime.mt]/query-args
#
$CGI{GET}->{out}->{putter}->{'mime.mt'}->{'query-args'}->{arg}->{blob} = {
	perl5_re	=>	'[a-z][a-z0-9]{0,7}:[[:graph:]]{32,128}',
	required	=>	'yes',
};
#
#  END: /cgi/GET/out/putter[@name=mime.mt]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='mime.mt']
#

#
#  BEGIN: /cgi/GET/out/putter[@name='dl.mt']
#
$CGI{GET}->{out}->{putter}->{'dl.mt'}->{name} = 'dl.mt';
$CGI{GET}->{out}->{putter}->{'dl.mt'}->{'content-type'} = 'text/html';

#
#  BEGIN: /cgi/GET/out/putter[@name=dl.mt]/query-args
#
$CGI{GET}->{out}->{putter}->{'dl.mt'}->{'query-args'}->{arg}->{mt} = {
	perl5_re	=>	'[[:graph:]]{1,64}',
	required	=>	'no',
};
$CGI{GET}->{out}->{putter}->{'dl.mt'}->{'query-args'}->{arg}->{lim} = {
	perl5_re	=>	'[1-9][0-9]{0,3}',
	default	=>	'10',
};
$CGI{GET}->{out}->{putter}->{'dl.mt'}->{'query-args'}->{arg}->{off} = {
	perl5_re	=>	'[+0-9]{1,10}',
	default	=>	'0',
};
#
#  END: /cgi/GET/out/putter[@name=dl.mt]/query-args
#

#
#  END: /cgi/GET/out/putter[@name='dl.mt']
#


#
#  BEGIN: /cgi/POST/in/putter[@name='post.mt']
#
$CGI{POST}->{in}->{putter}->{'post.mt'}->{name} = 'post.mt';
$CGI{POST}->{in}->{putter}->{'post.mt'}->{vars}->{var}->{mt} = {
	perl5_re	=>	'.*',
	required	=>	'no',
};
#
#  END: /cgi/POST/in/putter[@name=post.mt]/vars
#

#
#  END: /cgi/POST/in/putter[@name='post.mt']
#

$CGI{GET}->{out}->{putter}->{help}->{name} = 'help';
$CGI{GET}->{out}->{putter}->{help}->{'content-type'} = 'text/html';

require "httpd2.d/$ENV{REQUEST_METHOD}.pl";
