#!/bin/bash
#
#  Synopsis:
#	Invoke is-utf8wf on a fetched blob
#  Usage:
#	get-is-utf8wf <blob udig>
#  Exit Status:
#  	0	yes, blob is a well formed utf8
#	1	no, blob is not well formed utf8
#	2	blob is empty
#	3	blob does not exist
#  	4	wrong number of command line arguments
#	5	blobio get failed for unknown reason
#	6	is-utf8wf failed for unknown reason
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG* variables
#
PROG='get-is-utf8wf'
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $1" >&2
	exit $2
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die 'wrong number of arguments' 4
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	blobio empty --udig $BLOB && exit 2
	exit 3
	;;
*)
	die "blobio get failed: exit status=$STATUS" 5
	;;
esac

is-utf8wf <$TMP_BLOB
STATUS=$?
case $STATUS in
0|1|2)
	;;
*)
	die "is-utf8wf failed: exit status=$STATUS" 6
	;;
esac
exit $STATUS
