#!/bin/bash
#
#  Synopsis:
#	Merge the new-line count of a blob into the table new_line_count
#  Usage:
#	merge-new_line_count <blob udig>
#  Exit Status:
#  	0	count merged into table new_line_count
#	1	blob does not exist
#  	2	wrong number of command line arguments
#	3	blobio get failed for unknown reason
#	4	new-line-count failed for unknown reason
#	5	sql merge failed for unknown reason
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG* variables
#
PROG=merge-new_line_count
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $1" >&2
	exit $2
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die 'wrong number of arguments' 2
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS" 3
	;;
esac

COUNT=$(new-line-count <$TMP_BLOB)
test $? = 0 || die "new-line-count failed: exit status=$?" 4

psql --quiet --no-psqlrc <<END
insert into setspace.new_line_count(
	blob,
	line_count
  ) values (
  	'$BLOB'::udig,
	$COUNT
  ) on conflict
  	do nothing
;
END
test $? = 0 || die "psql insert failed: exit status=$?" 5

exit 0
