#!/usr/bin/env bash
# 
#  Synopsis:
#	Merge commands in <schema>/etc/<schema>.flow in table flowd_command
#  Usage:
#	merge-flowd_schema <schema1> <schema2> ...
#	echo "$SCHEMAs" | merge-flowd_schema
#  Exit Status:
#	0	all schema merged
#	1	unexpected error mering schema into db
#

PROG=$(basename $0)
PSQL='psql --quiet --no-psqlrc --no-readline'

die()
{
	local MSG="ERROR: $@"
	FAULT="$(date): $MSG"
	test -d run && (
		echo $FAULT >>run/$PROG.fault				||
			echo "WARN: echo >run/fault failed: exit status=$?" >&2
	)

	echo "$PROG: $FAULT" >&2
	exit 1
}

test -n "$SETSPACE_ROOT" || die 'env not defined: SETSPACE_ROOT'
cd $SETSPACE_ROOT || die "cd SETSPACE_ROOT failed: exit status=$?"

. etc/profile || die ". etc/profile failed: exit status=$?"

merge_schema_command()
{
	local SCHEMA=$1
	local FLOW="schema/$SCHEMA/etc/$SCHEMA.flow"

	test -e $FLOW || return 0
	awk '$0 ~ /^command/ {print $2}' $FLOW | while read CMD;  do
		case "$CMD" in
		[a-z]*)
			;;
		*)
			die "unexpected command: $CMD"
			;;
		esac

		$PSQL <<END || die "psql merge failed: exit status=$?"
INSERT INTO setops.flowd_command (
	schema_name,
	command_name
  ) VALUES('$SCHEMA', '$CMD')
      ON CONFLICT DO NOTHING
; 
END
	done
}

case $# in
0)
	while read SCH;  do
		merge_schema_command $SCH				||
			die "merge_schema_command failed: exit status=$?"
	done
	;;
*)
	for SCH in $@;  do
		merge_schema_command $SCH				||
			die "merge_flowd_command failed: exit status=$?"
	done
	;;
esac
exit 0
