#!/usr/bin/env bash
#
#  Synopsis:
#	Libexeced script for ssq to query faults, etc from schema setops.
#  Usage:
#	ssq setops service	#  List all blobs
#

PROG=$(basename $0)
PSQL='psql
	--quiet
	--no-psqlrc
	--tuples-only
	--no-readline
'

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# = 0 || die "bad cli arg count: got $#, expected 0"

$PSQL <<END || die "psql failed: exit status=$?"
SELECT
	blob
  FROM
  	setops.service
;
END
