#!/usr/bin/env bash
#
#  Synopsis:
#	Invoke is-utf8wf on a fetched blob
#  Usage:
#	get-is-utf8wf <blob udig>
#  Exit Status:
#  	0	yes, blob is a well formed utf8
#	1	no, blob is not well formed utf8
#	2	blob is empty and does not exist
#	3	blob does not exist
#  	4	unexpected error
#  Note:
#	Think about rewriting script to pipeline the blob instead of a
#	temporary file.
#
PROG=get-is-utf8wf
SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
SQL=$SCHEMA_ROOT/lib

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 4
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
BLOB=$1
UDIG="--udig $BLOB"

#  make work dir and change to that directory
source $SETSPACE_ROOT/lib/work-dir.bash				||
		die "source work-dir failed: exit status=$?"

#  fetch the blob into temp file

blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

is-utf8wf <BLOB 2>STDERR
STATUS=$?
test $STATUS -gt 2 && die "is-utf8wf failed: exit status=$STATUS"

exit 0
