#!/usr/bin/env bash
#
#  Synopsis:
#	Merge the 256 bitmap of all bytes into the table setcore.byte_bitmap
#  Usage:
#	merge-byte_bitmap <blob	udig>
#  Exit Status:
#  	0	bitmap merged into table byte_bitmap
#	1	blob does not exist
#  	2	wrong number of command line arguments
#	3	blobio get failed for unknown reason
#	4	byte-bitmap failed for unknown reason
#	5	sql merge failed for unknown reason
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG* variables
#	TMPDIR
#
PROG=merge-byte_bitmap
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $1" >&2
	exit $2
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die "wrong number of arguments: got $#, expected 1" 2
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS" 3
	;;
esac

HEX=$(byte-bitmap <$TMP_BLOB)
test $? = 0 || die "byte-bitmap failed: exit status=$?" 4
psql --quiet --no-psqlrc <<END
INSERT INTO setcore.byte_bitmap (
	blob,
	bitmap
  ) VALUES ( 
  	'$BLOB'::udig,
	X'$HEX'
  ) ON CONFLICT
  	DO NOTHING
;
END
test $? = 0 || die "psql insert failed: exit status=$?" 5

exit 0
