#!/usr/bin/env bash
#
#  Synopsis:
#	Upsert the 32 byte suffix of the blob into the table byte_suffix_32
#  Usage:
#	upsert-byte_suffix_32 <blob udig>
#  Exit Status:
#  	0	suffix upserted into table byte_suffix_32
#	1	blob does not exist
#	2	unknown error
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG* variables
#	TMPDIR
#  Note:
#	Consider pipelining blobs to eliminate dependence on TMPDIR.
#

PROG=upsert-byte_suffix_32
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 2
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die 'wrong number of arguments'
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

PREFIX=$(byte-suffix-32 $TMP_BLOB)
test $? = 0 || die "byte-suffix-32 failed: exit status=$?"

#  upsert new record
psql --quiet --no-psqlrc --set blob=$BLOB <<END
INSERT INTO setcore.byte_suffix_32 (
	blob,
	suffix
  ) VALUES (
  	:'blob'::udig,
	E'\\\\x$PREFIX'
  ) ON CONFLICT
  	DO NOTHING
;
END
test $? = 0 || die "psql insert failed: exit status=$?"

exit 0
