#!/usr/bin/env bash
#
#  Synopsis:
#	Merge the 32 byte suffix of the blob into the table byte_suffix_32
#  Usage:
#	merge-byte_suffix_32 <blob udig>
#  Exit Status:
#  	0	suffix merged into table byte_suffix_32
#	1	blob does not exist
#  	2	wrong number of command line arguments
#	3	blobio get failed for unknown reason
#	4	byte-suffix-32 failed for unknown reason
#	5	sql merge failed for unknown reason
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG* variables
#	TMPDIR
#  Note:
#	Consider pipelining blobs to eliminate dependence on TMPDIR.
#

PROG=merge-byte_suffix_32
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	STATUS=$1
	shift

	echo "$PROG: ERROR: $@" >&2
	exit $STATUS
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die 2 'wrong number of arguments'
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die 3 "blobio get failed: exit status=$STATUS"
	;;
esac

PREFIX=$(byte-suffix-32 $TMP_BLOB)
test $? = 0 || die 4 "byte-suffix-32 failed: exit status=$?"

#  merge new record
psql --quiet --no-psqlrc <<END
INSERT INTO setcore.byte_suffix_32 (
	blob,
	suffix
  ) VALUES (
  	'$BLOB'::udig,
	E'\\\\x$PREFIX'
  ) ON CONFLICT
  	DO NOTHING
;
END
test $? = 0 || die 5 "psql insert failed: exit status=$?"

exit 0
