#!/bin/bash
#
#  Synopsis:
#	Merge the 32 byte prefix of the blob into the table byte_prefix_32
#  Usage:
#	merge-byte_prefix_32 <blob udig>
#  Exit Status:
#  	0	prefix merged into table byte_prefix_32
#	1	blob does not exist
#  	2	wrong number of command line arguments
#	3	blobio get failed for unknown reason
#	4	byte-prefix-32 failed for unknown reason
#	5	sql merge failed for unknown reason
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	PG* variables
#	TMPDIR
#  Note:
#	Consider pipelining blobs to eliminate dependence on TMPDIR.
#

PROG=merge-byte_prefix_32
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $1" >&2
	exit $2
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die 'wrong number of arguments' 2
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS" 3
	;;
esac

PREFIX=$(byte-prefix-32 <$TMP_BLOB)
test $? = 0 || die "byte-prefix-32 failed: exit status=$?" 4

#  merge new record
psql --quiet --no-psqlrc <<END
INSERT INTO setcore.byte_prefix_32 (
	blob,
	prefix
  ) VALUES (
  	'$BLOB'::udig,
	E'\\\\x$PREFIX'
  ) ON CONFLICT
  	DO NOTHING
;
END
test $? = 0 || die "psql insert failed: exit status=$?" 5

exit 0
