#!/usr/bin/env bash
#
#  Synopsis:
#	Find symeteric difference difference of {setcore,blobio}.service blobs
#  Usage:
#	. $SETSPACE_ROOT/schema/setcore/etc/profile
#	service-xor-yesterday >service-xor-yesterday.out
#  Note:
#	Simplify by eliminating the BLOBIO_PG* vars.
#
#	PGPASSWORD is ignored.
#

PROG=$(basename $0)
SINCE=
DISCOVERY_QUAL=

export PGHOST=${PGHOST:=/tmp}
export PGPORT=${PGPORT:=5432}
export PGUSER=${PGUSER:=$USER}
export PGDATABASE=${PGDATABASE:=$USER}

export BLOBIO_PGHOST=${BLOBIO_PGHOST:=$PGHOST}
export BLOBIO_PGPORT=${BLOBIO_PGPORT:=$PGPORT}
export BLOBIO_PGUSER=${BLOBIO_PGUSER:=$PGUSER}
export BLOBIO_PGDATABASE=${BLOBIO_PGDATABASE:=$PGDATABASE}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

comm -3							\
<(							\
psql							\
	--var since=yesterday				\
	--host $BLOBIO_PGHOST				\
	--port $BLOBIO_PGPORT				\
	--user $BLOBIO_PGUSER				\
	--dbname $BLOBIO_PGDATABASE			\
	--no-align					\
	--tuples-only					\
	--quiet						\
	--no-psqlrc					\
	<<EOF
SELECT
	blob::text
  FROM
  	blobio.service
  WHERE
  	discover_time >= :'since'
  ORDER BY
  	1 asc
EOF
)							\
<(
psql							\
	--var since=yesterday				\
	--no-align					\
	--tuples-only					\
	--quiet						\
	--no-psqlrc					\
	<<EOF2
SELECT
	blob::text
  FROM
  	setcore.service
  WHERE
  	discover_time >= :'since'
  ORDER BY
  	1 asc
EOF2
)
