#!/usr/bin/env bash
#
#  Synopsis:
#	Find symmetric difference of blobio.service and setcore.service tables
#  Usage:
#	. $SETSPACE_ROOT/schema/setcore/etc/profile
#	service-xor >service-xor.out
#  Note:
#	Simplify by eliminating the BLOBIO_PG* vars.
#
#	Added timestamp or interval option.
#
#	PGPASSWORD is ignored.
#

PROG=$(basename $0)
SINCE=
DISCOVERY_QUAL=

export PGHOST=${PGHOST:=/tmp}
export PGPORT=${PGPORT:=5432}
export PGUSER=${PGUSER:=$USER}
export PGDATABASE=${PGDATABASE:=$USER}

export BLOBIO_PGHOST=${BLOBIO_PGHOST:=$PGHOST}
export BLOBIO_PGPORT=${BLOBIO_PGPORT:=$PGPORT}
export BLOBIO_PGUSER=${BLOBIO_PGUSER:=$PGUSER}
export BLOBIO_PGDATABASE=${BLOBIO_PGDATABASE:=$PGDATABASE}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

comm -3							\
<(							\
psql							\
	--host $BLOBIO_PGHOST				\
	--port $BLOBIO_PGPORT				\
	--user $BLOBIO_PGUSER				\
	--dbname $BLOBIO_PGDATABASE			\
	--no-align					\
	--tuples-only					\
	--quiet						\
	--no-psqlrc					\
	--command 					\
"
SELECT
	blob::text
  FROM
  	blobio.service
  ORDER BY
  	1 asc
")							\
<(
psql							\
	--no-align					\
	--tuples-only					\
	--quiet						\
	--no-psqlrc					\
	--command 					\
"
SELECT
	blob::text
  FROM
  	setcore.service
  ORDER BY
  	1 asc
")
