#!/usr/bin/env bash
#
#  Synopsis:
#	query setcore schema for blobs in service
#
PROG=$(basename $0)

PSQL='psql
	--no-align
	--set=ON_ERROR_STOP=1
	--no-psqlrc
	--tuples-only
	--pset null=Unknown
	--quiet
	--no-readline
'
SQL=lib/$PROG.sql

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

ACTION="$1";  shift;
case $ACTION in
'')
	;;
*)
	LIBEXEC=libexec/ssq-setcore-service-$ACTION
	test -x $LIBEXEC || die "no libexec for action: $ACTION"
	exec $LIBEXEC #@
	;;
esac

$PSQL --file $SQL || die "psql setcore.service failed: exit status=$?"
