#!/usr/bin/env bash
#
#  Synopsis:
#	list rummy blobs, existing in setcore but not in service
#  Usage:
#	ssq setcore rummy | wc -l
#  Note:
#	Need to add "rummy ls" to see detail of what is known about a rummied
#	blob.
#
PROG=$(basename $0)

PSQL='psql
	--no-align
	--set=ON_ERROR_STOP=1
	--no-psqlrc
	--tuples-only
	--pset null=Unknown
	--quiet
	--no-readline
'

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

case $# in
0)
	SQL=lib/$PROG.sql
	;;
1)
	test "$1" = count || die "unknown action: $1"
	exec libexec/$PROG-count
	;;
*)
	die "wrong cli arg: got $#, need <= 1"
	;;
esac

$PSQL --file $SQL || die "psql rummy failed: exit status=$?"
