#!/usr/bin/env bash
#
#  Synopsis:
#	list recent blobs in setcore which may not be in service
#
PROG=$(basename $0)

PSQL='psql
	--set=ON_ERROR_STOP=1
	--no-psqlrc
	--no-readline
'

help()
{
	echo "usage: $PROG"
}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

test $# = 0 || die "wrong number of cli arg: got $#, want 1"

$PSQL --expanded <<END || die "psql recent failed: exit status=$?"
SELECT
	s.blob AS "Blob",
	regexp_replace(age(now(), s.discover_time)::text, '\..*', '') || ' ago'
                AS "Age",
	pg_size_pretty(bc.byte_count) AS "Size",
	CASE
	  WHEN u8.is_utf8 IS NULL THEN
	  	'Unknown'
          WHEN u8.is_utf8 THEN
	  	'Yes'
	  ELSE
	  	'No'
	END AS "UTF-8",
	CASE
	  WHEN p32.prefix IS NULL THEN
	  	'Unknown'
	  ELSE
	  	encode(p32.prefix, 'escape')
	END AS "32 Byte Prefix",
	CASE
	  WHEN p32.prefix IS NULL THEN
	  	'Unknown'
	  ELSE
	  	encode(p32.prefix, 'escape')
	END AS "32 Byte Suffix",
	bb.bitmap::text AS "Byte Bitmap",
	CASE
	  WHEN rum.blob IS NULL THEN
	  	'No'
	  ELSE
	  	'Yes'
	END AS "Is Rummy"
  FROM
  	setcore.service s
	  LEFT OUTER JOIN setcore.byte_count bc ON (bc.blob = s.blob)
	  LEFT OUTER JOIN setcore.is_utf8wf u8 ON (u8.blob = s.blob)
	  LEFT OUTER JOIN setcore.byte_prefix_32 p32 ON (p32.blob = s.blob)
	  LEFT OUTER JOIN setcore.byte_suffix_32 s32 ON (s32.blob = s.blob)
	  LEFT OUTER JOIN setcore.byte_bitmap bb ON (bb.blob = s.blob)
	  LEFT OUTER JOIN setcore.rummy rum ON (rum.blob = s.blob)
  ORDER BY
  	s.discover_time DESC,
	bc.byte_count DESC,
	s.blob ASC
  LIMIT
  	10
END
