#!/usr/bin/env bash
#
#  Synopsis:
#	setcore schema querier backend libexeced by front end script "ssq".
#  Usage:
#	BLOB=btc20:b0e889a067b5d4fff15c3d6e646554939a793783
#
#	ssq setcore help
#  Note:
#	Think about adding "Is Rummy".  Does being a rummy imply nt in service?
#
PROG=$(basename $0)

help()
{
	echo "usage: $PROG [service|ls|rummy]"
}

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 1
}

if [ $# = 0 ];  then
	help
	exit 0
fi
ACTION=$1
shift

cd schema/setcore || die "cd schema/setcore failed: exit status=$?"

test -r etc/profile && . etc/profile

case "$ACTION" in
help)
	help
	exit 0
	;;
service)
	exec libexec/ssq-setcore-service
	;;
ls)
	test $# = 0 && exec libexec/ssq-setcore-ls-recent
	exec libexec/ssq-setcore-ls $@
	;;
*)
	die "unknown action: $ACTION"
	;;
esac
