#!/usr/bin/env bash
#
#  Synopsis:
#	Upserted the 32 byte suffix of the blob into the table byte_suffix_32
#  Usage:
#	upsert-byte_suffix_32 <blob udig>
#  Exit Status:
#  	0	suffix upserted into table byte_suffix_32
#	1	blob does not exist
#  	2	unknown error
#

PROG=upsert-byte_suffix_32
PSQL='psql
	--quiet
	--no-psqlrc
	--no-readline
'
SQL=$SCHEMA_ROOT/lib/$PROG.sql
SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"

die()
{
	echo "$PROG: ERROR: $@" >&2
	exit 2
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
BLOB=$1
UDIG="--udig $BLOB"

#  make work dir and change to that directory
source $SETSPACE_ROOT/lib/work-dir.bash				||
		die "source work-dir failed: exit status=$?"

#  fetch the blob into temp file

blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

SUFFIX=$(byte-suffix-32 BLOB 2>STDERR)
STATUS=$?
test $STATUS = 0 || die "byte-suffix-32 failed: exit status=$STATUS"

#  upsert new record
$PSQL --set blob=$BLOB --set suffix=$SUFFIX --file $SQL			||
			die "psql upsert failed: exit status=$?"

exit 0
