#!/usr/bin/env bash
#
#  Synopsis:
#	Merge the 32 byte prefix of the blob into the table byte_prefix_32
#  Usage:
#	merge-byte_prefix_32 <blob udig>
#  Exit Status:
#  	0	prefix merged into table byte_prefix_32
#	1	blob does not exist
#  	2	unknown error
#

PROG=upsert-byte_prefix_32
PSQL='psql
	--quiet
	--no-psqlrc
	--no-readline
'
SQL=lib/$PROG.sql
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG.$$

die()
{
	echo "$PROG: ERROR: $1" >&2
	exit 2
}

leave()
{
	rm -f $TMP_BLOB
	exit
}

trap leave EXIT INT TERM QUIT

test $# = 1 || die 'wrong number of arguments'
BLOB=$1

#  fetch the blob into temp file

blobio get --service $BLOBIO_GET_SERVICE --udig $BLOB --output-path $TMP_BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

PREFIX=$(byte-prefix-32 <$TMP_BLOB)
test $? = 0 || die "byte-prefix-32 failed: exit status=$?"

#  merge new record
$PSQL --set blob=$BLOB --set prefix=$PREFIX --file $SQL
test $? = 0 || die "psql upsert failed: exit status=$?"

exit 0
