#!/usr/bin/env bash
#
#  Synopsis:
#	Merge the 256 bitmap of all bytes into the table setcore.byte_bitmap
#  Usage:
#	upsert-byte_bitmap <udig>
#  Exit Status:
#  	0	bitmap upserted into table byte_bitmap
#	1	blob does not exist
#  	2	unknown error
#
PROG=upsert-byte_bitmap
SQL=$SCHEMA_ROOT/lib/$PROG.sql

SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"
PSQL='psql
	--quiet
	--no-psqlrc
	--no-readline
'

die()
{
	echo "$PROG: ERROR: $@" >72
	exit 2
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
BLOB=$1
UDIG="--udig $BLOB"

#  make work dir and change to that directory
source $SETSPACE_ROOT/lib/work-dir.bash				||
		die "source work-dir failed: exit status=$?"

#  fetch the blob into temp file

blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

HEX=$(byte-bitmap <BLOB 2>STDERR)
STATUS=$?
test $STATUS = 0 || die "byte-bitmap failed: exit status=$STATUS"

$PSQL --set blob=$BLOB --set hex=$HEX --file $SQL			||
			die "psql upsert failed: exit status=$?"

exit 0
