#!/usr/bin/env bash
#
#  Synopsis:
#	Merge the 32 byte prefix of the blob into the table byte_prefix_32
#  Usage:
#	merge-byte_prefix_32 <blob udig>
#  Exit Status:
#  	0	prefix merged into table byte_prefix_32
#	1	blob does not exist
#  	2	unknown error
#

PROG=upsert-byte_prefix_32
PSQL='psql
	--quiet
	--no-psqlrc
	--no-readline
'
SQL=$SCHEMA_ROOT/lib/$PROG.sql
SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"

die()
{
	setcore-fault upsert_byte_prefix_32 "$BLOB" "$@"
	exit 2
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1"
BLOB=$1
UDIG="--udig $BLOB"

#  make work dir and change to that directory
source $SETSPACE_ROOT/lib/work-dir.bash				||
		die "source work-dir failed: exit status=$?"

#  fetch the blob into temp file

blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

PREFIX=$(byte-prefix-32 <BLOB 2>STDERR )
test $? = 0 || die "byte-prefix-32 failed: exit status=$?"

#  merge new record
$PSQL --set blob=$BLOB --set prefix=$PREFIX --file $SQL
test $? = 0 || die "psql upsert failed: exit status=$?"

exit 0
