#!/usr/bin/env bash
#
#  Synopsis:
#	Merge the byte count of a blob into the table byte_count
#  Usage:
#	upsert-byte_count <blob udig>
#  Exit Status:
#  	0	count merged into table byte_count
#	1	blob does not exist
#  	2	unknown error
#
PROG=upsert-byte_count
PSQL='psql
	--quiet
	--no-psqlrc
	--no-readline
'
SQL=$SCHEMA_ROOT/lib/$PROG.sql
SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"

die()
{
	setcore-fault upsert_byte_count "$BLOB" "$@"
	exit 2
}

test $# = 1 || die 'wrong number of arguments'
BLOB=$1
UDIG="--udig $BLOB"

#  make work dir and change to that directory
source $SETSPACE_ROOT/lib/work-dir.bash				||
		die "source work-dir failed: exit status=$?"

#  fetch the blob into temp file

blobio get $SERVICE $UDIG --output-path BLOB 2>STDERR
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get failed: exit status=$STATUS"
	;;
esac

COUNT=$(byte-count <BLOB 2>STDERR)
STATUS=$?
test $STATUS = 0 || die "byte-count failed: exit status=$STATUS"

$PSQL --set blob=$BLOB --set count=$COUNT --file $SQL			||
			die "psql upsert failed: exit status=$?"

exit 0
