#!/bin/bash
#
#  Synopsis:
#	Append a brr for each page of utf8 text in a pdf file.
#  Usage:
#	append-page-pgtexts-brr <path-to-brr-file> <pdf-udig> 
#  Exit Status
#	0	append all utf8 pages of a pdf document to a blob request log
#	1	wrong number of arguments
#	2	unexpected sql error
#	3	unexpected error appending brr
#

PROG=append-page-pgtexts-brr

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

test $# = 2 || die 'wrong number of arguments' 1
BRR_PATH=$1
PDF_UDIG=$2

psql --no-psqlrc --quiet <<END | while read PAGE_UDIG BYTE_COUNT;  do
\\pset tuples_only on
\\pset format unaligned
\\pset fieldsep '\\t'

SELECt
	p8.page_blob,
	bc.byte_count
  FROM
  	pdfbox.extract_page_utf8 p8
	  JOIN setcore.byte_count bc ON (bc.blob = p8.page_blob)
  WHERE
  	p8.pdf_blob = '$PDF_UDIG'
	AND
	bc.blob = p8.page_blob
END
	append-brr $BRR_PATH						\
	$(RFC3339Nano)							\
	'fs~schema=pdfbox'						\
	put								\
	$PAGE_UDIG							\
	ok								\
	$BYTE_COUNT							\
	0.000000000							||
		die "append-brr failed: exit status=$?"
done
STATUS=${PIPESTATUS[*]}
case "$STATUS" in
'0 0')
	;;
'* 0')
	die "pipeline sql error: exit status=$STATUS" 2
	;;
'0 *')
	die "pipeline append-brr error: exit status=$STATUS" 3
	;;
*)
	die "pipeline sql | append error: exit status=$STATUS" 2
	;;
esac
