#!/bin/bash
#
#  Synopsis:
#	Append a brr for the utf8 blob of a pdf blob to the pgtexts spool.
#  Usage:
#	append-pgtexts-brr <path-to-brr-file> <pdf-udig> 
#  Exit Status
#	0	append utf8 text brr record to <path-to-brr-file>
#	1	byte_count tuple does not exist
#	2	wrong number of arguments
#	3	unexpected sql error
#	4	unexpected error appending brr
#  Note:
#	Should the verb be a passed argument
#

PROG=append-pgtexts-brr

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

test $# = 2 || die 'wrong number of arguments' 2
BRR_PATH=$1
PDF_UDIG=$2

TUPLE=$(psql --no-psqlrc --quiet --tuples-only <<END
\\set ON_ERROR_STOP on
\\pset tuples_only on
\\pset format unaligned
\\pset fieldsep '\\t'

SELECT
	u8.utf8_blob,
	bc.byte_count
  FROM
  	pdfbox.extract_text_utf8 u8
	  INNER JOIN setcore.byte_count bc ON (bc.blob = u8.utf8_blob)
  where
  	u8.blob = '$PDF_UDIG'
	AND
	u8.utf8_blob IS NOT NULL
END
)
test $? = 0 || die "psql failed: exit status=$?" 3

read UTF8_UDIG BYTE_COUNT <<<$TUPLE
test -n "$UTF8_UDIG" -a -n "$BYTE_COUNT" || exit 1

append-brr $BRR_PATH							\
	$(RFC3339Nano)							\
	'fs~schema=pdfbox'						\
	put								\
	$UTF8_UDIG							\
	ok								\
	$BYTE_COUNT							\
	0.000000000
test $? = 0 || die "append-brr failed: exit status=$?" 4
