#!/bin/bash
#
#  Synopsis:
#	Append any unmerged utf8 pdf text blobs into pgtexts.tsv_utf8/spool
#  Usage:
#	PDFBOX_ROOT=/usr/local/setspace/schema/pdfbox
#	BRR_LOG=$PDFBOX_ROOT/schema/pgtexts/spool/pdfbox.brr
#	LOG=$PDFBOX_ROOT/log/cron-merge-tsv_utf8.log
#
#	* * * * * sbin/cron-merge-tsv_utf8 $BRR_LOG '-1 Hour' >>$LOG 2>&1
#

PROG=cron-unmergeed-tsv_utf8
PGTEXTS_SPOOL=../

log()
{
	echo "$(date +'%Y/%m/%d %H:%M:%S' ): $PROG: $@"
}

die()
{
	log "ERROR: $@" >&2
	exit 1
}

leave()
{
	log 'good bye, cruel world'
}

trap leave EXIT
log 'hello, world'

test $# = 2 || die 'wrong number of arguments'
BRR_LOG=$1
SINCE=$2

test -n "$PDFBOX_ROOT" || die 'environment variable not defined PDFBOX_ROOT'
log "PDFBOX_ROOT=$PDFBOX_ROOT"
cd $PDFBOX_ROOT || die "cd $PDFBOX_ROOT failed"

test -e etc/profile || die "missing expected profile: $(pwd)/etc/profile"
log 'sourcing etc/profile ...'
. etc/profile

log "brr log: $BRR_LOG"
log "since: $SINCE"

log 'dumping PG variables ...'
env | grep '^PG' | while read E;  do
	log $E
done

SQL=lib/unmerged-tsv_utf8.sql
psql -f $SQL --quiet --no-psqlrc --set since="'$SINCE'" | while read UDIG; do
	log $UDIG
	append-pgtexts-brr $BRR_LOG $UDIG ||
		die "append-pgtexts-brr failed: exit status=$?"
done
