#!/bin/bash
#
#  Synopsis:
#	Extract UTF8 text from PDF and store results in json blob.
#  Description:
#	A well defined pdf file is fancy.
#  Usage:
#	json-extract_utf8 <udig>
#  Exit Status:
#	0	extracted utf8 text and stored json blob
#	1	text not extracted
#	2	blob does not exist
#	3	wrong number of arguments
#	4	blobio get error
#	5	blobio eat error
#	6	java ExtractText failed
#	7	json error
#  Java Environment:
#	The jar of pdfbox, version 2, must be in the CLASSPATH.
#  Environment:
#	BLOBIO_ALGORITHM=${BLOBIO_ALGORITHM:=sha}
#	BLOBIO_SERVICE=${BLOBIO_SERVICE:=localhost:1797}
#	PDFBOX_JAR

#

PROG=json-extract_utf8

TMP_BLOB=${TMP_DIR:=/tmp}/$PROG-$$.pdf
TMP_ERR=${TMP_DIR:=/tmp}/$PROG-$$.err
TMP_UTF8=${TMP_DIR:=/tmp}/$PROG-$$.utf8
TMP_JSON=${TMP_DIR:=/tmp}/$PROG-$$.json

leave()
{
	rm -f $TMP_BLOB $TMP_ERR $TMP_UTF8 $TMP_JSON
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $@" >&2
	exit $STATUS
}

test $# = 1 || die 'wrong number of arguments' 2
UDIG=$1

#  fetch the pdf blob

blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_SERVICE
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die 'blobio get failed' 3
	;;
esac

put_file()
{
	FP=$1
	if [ ! -r $FP ];  then
		echo null
		return
	fi

	DIG=$(
		blobio eat					\
			--input-path $FP			\
			--algorithm $BLOBIO_ALGORITHM		\
	)
	test $? = 0 ||  die "blobio eat failed: exit status=$?"
	FILE_UDIG=$BLOBIO_ALGORITHM:$DIG
	blobio put --udig $FILE_UDIG --input-path $FP --service $BLOBIO_SERVICE
	test $? = 0 || die "blobio put failed: exit status=$?" 5
	echo '"'$FILE_UDIG'"'
}

#  execute the java extract.  we expect only 0 or 1 as an exit status

java -jar $PDFBOX_JAR ExtractText $TMP_BLOB $TMP_UTF8 2>$TMP_ERR
EXIT_STATUS=$?
test $EXIT_STATUS = 0 && rm $TMP_ERR

cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 7
{
	"pdfbox2.setspace.com": {
		"extract_utf8": {
			"blob":		"$UDIG",
			"exit_status":	$STATUS,
			"utf8_blob": 	$(put_file $TMP_UTF8),
			"stderr_blob":	$(put_file $TMP_ERR)
		},
		"date":		"$(date)",
		"hostname":	"$(hostname)",
		"USER":		"$USER"
	}
}
END

put_file $TMP_JSON >/dev/null 
exit 0
