#!/bin/bash
#
#  Synopsis:
#	Extract UTF8 text from proven PDF and store results in json blob.
#  Usage:
#	json-extract_utf8 <udig>
#  Exit Status:
#	0	extracted utf8 text and stored json blob
#	1	blob does not exist
#	2	wrong number of arguments
#	3	PDFBOX2_JAR not defined or file does not exist
#	4	blobio error
#	5	json error
#  Java Environment:
#	The jar of pdfbox, version 2, must be in the CLASSPATH.
#  Environment:
#	BLOBIO_ALGORITHM=${BLOBIO_ALGORITHM:=sha}
#	BLOBIO_SERVICE=${BLOBIO_SERVICE:=localhost:1797}
#	PDFBOX2_JAR
#

PROG=json-extract_utf8

TMP_BLOB=${TMP_DIR:=/tmp}/$PROG-$$.pdf
TMP_ERR=${TMP_DIR:=/tmp}/$PROG-$$.err
TMP_UTF8=${TMP_DIR:=/tmp}/$PROG-$$.utf8
TMP_JSON=${TMP_DIR:=/tmp}/$PROG-$$.json

leave()
{
	rm -f $TMP_BLOB $TMP_ERR $TMP_UTF8 $TMP_JSON
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $@" >&2
	exit $STATUS
}

test $# = 1 || die 'wrong number of arguments' 2
UDIG=$1

#  Note: ought to be in CLASSPATH!
test -n "$PDFBOX2_JAR" || die "environment not defined: PDFBOX2_JAR" 3
test -e $PDFBOX2_JAR || die "jar file does not exist: $PDFBOX2_JAR" 3

#  fetch the pdf blob

blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_SERVICE
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die 'blobio get failed' 4
	;;
esac

put_file()
{
	FP=$1
	if [ ! -e $FP ];  then
		echo null
		return
	fi

	DIG=$(
		blobio eat					\
			--input-path $FP			\
			--algorithm $BLOBIO_ALGORITHM		\
	)
	test $? = 0 ||  die "blobio eat failed: exit status=$?" 4
	FILE_UDIG=$BLOBIO_ALGORITHM:$DIG
	blobio put --udig $FILE_UDIG --input-path $FP --service $BLOBIO_SERVICE
	test $? = 0 || die "blobio put failed: exit status=$?" 4
	echo '"'$FILE_UDIG'"'
}

#  execute the java extract.

java -jar $PDFBOX2_JAR ExtractText $TMP_BLOB $TMP_UTF8 2>$TMP_ERR
EXIT_STATUS=$?

cat >$TMP_JSON <<END || die "cat >json failed: exit status: $?" 5
{
	"pdfbox2.setspace.com": {
		"extract_utf8": {
			"blob":		"$UDIG",
			"exit_status":	$EXIT_STATUS,
			"utf8_blob": 	$(put_file $TMP_UTF8),
			"stderr_blob":	$(put_file $TMP_ERR)
		},
		"date":		"$(date)",
		"hostname":	"$(hostname)",
		"USER":		"$USER"
	}
}
END

put_file $TMP_JSON >/dev/null 
exit 0
