#!/bin/bash
#
#  Synopsis:
#	Extract and merge the PDDocumentInformation scalars from PDF.
#  Usage:
#	merge-pddocument_information <udig>
#  Exit Status:
#	0	ok, extracted pddocument info and stored into PostgreSQL
#	1	pdf load ok but some fields do not satify database constraints.
#	2	pdf load failed
#	3	blob does not exist
#	4	script invocation or setup error
#	5	unexpected blobio error
#	6	unexpected java putPDDocument failed
#	7	pg database error
#  Environment:
#	BLOBIO_ALGORITHM
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	TMPDIR
#  Note:
#	How do we know the output of putPDDocumentInformation is always UTF-8?
#

START_TIME=$(RFC3339Nano)
PROG=merge-pddocument_information
PSQL='psql --no-psqlrc --quiet'
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
ALGORITHM=${BLOBIO_ALGORITHM:=btc20}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.pdf
TMP_STDERR=${TMPDIR:=/tmp}/$PROG-$$.err
TMP_ROW=${TMPDIR:=/tmp}/$PROG-$$.row

leave()
{
	STATUS=$?
	rm -f $TMP_BLOB $TMP_STDERR $TMP_ROW
	exit $STATUS
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

_fault()
{
	source $SETSPACE_ROOT/lib/fault-process.sh ||
			die "source fault-process.sh failed: exit status=$?" 3
	fault_process							\
		pdfbox							\
		pddocument_information					\
		$UDIG							\
		"$1"							\
		$TMP_STDERR						\
		$2							\
		$START_TIME
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1" 4
UDIG=$1

#  fetch the pdf blob

blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_GET_SERVICE
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 3
	;;
*)
	die "blobio get pdf failed: exit status=$STATUS" 5
	;;
esac

#  execute the java extract.  although we expect only 0 and no stderr,
#  0 with stderr is normal.  an exit status of 3 indicates a failed load
#  of the pdf file.

java <$TMP_BLOB								\
	-server								\
	-cp $CLASSPATH putPDDocumentInformation 			\
	>$TMP_ROW 2>$TMP_STDERR
STATUS=$?
test -e $TMP_STDERR || die "java write to stderr failed" 4
case $STATUS in
0)
	EXIT_STATUS=0
	;;
2)
	EXIT_STATUS=1
	;;
*)
	_fault "java putPDDocumentInformation failed: exit status=$STATUS" 6
	;;
esac

merge-stdin-pddocument_information					\
	$UDIG								\
	$(file-stat-size $TMP_ROW) <$TMP_ROW				||
	die "merge-stdin-pddocument_information failed: exit status=$?" 7
exit $EXIT_STATUS
