#!/bin/bash
#
#  Synopsis:
#	Extract the PDDocumentInformation scalars from PDF and merge into PG
#  Usage:
#	merge-pddocument <udig>
#  Exit Status:
#	0	ok, extracted pddocument info and stored into PostgreSQL
#	1	pdf load failed
#	2	blob does not exist
#	3	invocation error
#	4	unexpected blobio error
#	5	unexpected java putPDDocument failed
#	6	pg database error
#	7	infomation data violates database constraint
#  Environment:
#	BLOBIO_ALGORITHM
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	TMPDIR
#  Note:
#	How do we know the output of putPDDocumentInformation is always UTF-8?
#

PROG=merge-pddocument_information
BLOBIO_GET_SERVICE=${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}
ALGORITHM=${BLOBIO_ALGORITHM:=bc160}

TMP_BLOB=${TMPDIR:=/tmp}/$PROG-$$.pdf
TMP_STDERR=${TMPDIR:=/tmp}/$PROG-$$.err
TMP_ROW=${TMPDIR:=/tmp}/$PROG-$$.row

leave()
{
	#rm -f $TMP_BLOB $TMP_STDERR $TMP_ROW
	true
}
trap leave EXIT

die()
{
	STATUS=$2
	echo "$PROG: ERROR: $1" >&2
	exit $STATUS
}

ERROR()
{
	echo "$PROG: ERROR: $@" >&2
}

test $# = 1 || die "wrong number of arguments: got $#, expected 1" 3
UDIG=$1

#  fetch the pdf blob

blobio get --udig $UDIG --output-path $TMP_BLOB --service $BLOBIO_GET_SERVICE
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 2
	;;
*)
	die 'blobio get failed' 4
	;;
esac

#  execute the java extract.  although we expect only 0 and no stderr,
#  0 with stderr is normal.  an exit status of 1 indicates a failed load
#  of the pdf file.

java -cp $CLASSPATH putPDDocumentInformation <$TMP_BLOB >$TMP_ROW 2>$TMP_STDERR
EXIT_STATUS=$?
test -e $TMP_STDERR || die "java write to stderr failed" 5
cat $TMP_STDERR >&2

if [ $EXIT_STATUS != 0 ];  then
	STDERR_UDIG=$ALGORITHM:$(
		blobio eat --algorithm $ALGORITHM --input-path $TMP_STDERR
	)
	blobio put							\
		--udig $STDERR_UDIG					\
		--input-path $TMP_STDERR				\
		--service $BLOBIO_SERVICE				||
		die "blobio put stderr failed: exit status=$?" 4
	$PSQL <<END || die "psql insert fault failed: exit status=$?" 6
INSERT INTO pdfbox.fault_pddocument_information (
	blob,
	exit_status,
	stderr_blob
) VALUES (
	'$UDIG',
	$EXIT_STATUS,
	'$STDERR_UDIG'
)
END
	test $EXIT_STATUS = 2 || die "java failed: exit status=$EXIT_STATUS" 5
	exit 1
fi

merge-stdin-pddocument_information 					\
	$UDIG								\
	$(file-stat-size $TMP_ROW) <$TMP_ROW				||
	die "merge-stdin-pddocument_information failed: exit status=$?" 6
exit 0
