#!/usr/bin/env bash
#
#  Synopsis:
#	List blobs in view pdfbox.fault
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE='[count]'
SQL=lib/$PROG.sql
PSQL=$SSQ_COMMON_PSQL_TSV

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql fault failed: exit status=$?"
	exit 0
fi
exec_action $@
