#!/usr/bin/env bash
#
#  Synopsis:
#	Count blobs in table pdfbox.blob
#
source $SETSPACE_ROOT/lib/ssq-common.bash

USAGE=''
SQL=lib/$PROG.sql
PSQL=$SSQ_COMMON_PSQL_TSV

if [ $# = 0 ];  then
	$PSQL --file $SQL || die "psql blob count failed: exit status=$?"
	exit 0
fi

exec_action $@
