#!/usr/bin/env bash
#
#  Synopsis:
#	pdfbox schema querier backend libexeced by front end script "ssq".
#  Note:
#	Think about adding "Is Rummy".  Does being a rummy imply nt in service?
#
source $SETSPACE_ROOT/lib/ssq-common.bash
USAGE='[service|rummy|fault] | <udig>...'

exec_help $@
exec_udig $@
exec_action $@
