#!/usr/bin/env bash
#
#  Synopsis:
#	Extract and upsert the PDDocumentInformation scalars from PDF.
#  Usage:
#	upsert-pddocument_information <udig>
#  Exit Status:
#	0	ok, extracted pddocument info and stored into PostgreSQL
#	1	blob does not exist
#	2	unexpected error
#  Environment:
#	BLOBIO_SERVICE
#	BLOBIO_GET_SERVICE
#	TMPDIR
#  Note:
#	How do we know the output of putPDDocumentInformation is always UTF-8?
#

PROG=upsert-pddocument_information
PSQL='psql --no-psqlrc --quiet --no-readline'
SERVICE="--service ${BLOBIO_GET_SERVICE:=$BLOBIO_SERVICE}"

WORK_DIR=${TMPDIR:=/tmp}/$PROG-$$.d

leave()
{
	rm --recursive --force $WORK_DIR				||
		echo "$PROG: ERROR: rm work dir failed: exit status=$?" >&2
}

trap leave EXIT
trap '' PIPE

die()
{
	test -s STDERR && cat STDERR >&2
	test -s STDOUT && echo "$PROG: WARN: stdout is not empty" >&2
	echo "$PROG: ERROR: $@" >&2
	exit 2
}

jdie()
{
	die "java putPDDocumentInformation failed: $@"
}

test $# = 1 || die "wrong number of arguments: got $#, need 1"
PDF_UDIG=$1

mkdir $WORK_DIR || die "mkdir work failed: exit status=$?"
cd $WORK_DIR || die "cd work dir failed: exit status=$?"

UDIG="--udig $PDF_UDIG"

#  fetch the pdf blob

blobio get $UDIG $SERVICE --output-path BLOB
STATUS=$?
case $STATUS in
0)
	;;
1)
	exit 1
	;;
*)
	die "blobio get pdf failed: exit status=$STATUS"
	;;
esac

#  execute the java extract.  although we expect only 0 and no stderr,
#  0 with stderr is normal.  an exit status of 3 indicates a failed load
#  of the pdf file.

java <BLOB								\
	-server								\
	-cp $CLASSPATH putPDDocumentInformation 			\
	>ROW 2>STDERR
STATUS=$?
test -e STDERR || die 'java write to stderr failed'
test -e ROW || die 'java write to row failed'

case $STATUS in
0)
	;;
2)
	jdie 'violation of db constraints: exit status=2'
	;;
3)
	jdie 'load of pdf failed: exit status=3'
	;;
4)
	jdie 'invocation failed: exit status=4'
	;;
5)
	jdie 'unexpected java error: exit status=5'
	;;
esac

upsert-stdin-pddocument_information					\
	$PDF_UDIG							\
	$(file-stat-size ROW) <ROW					||
	die "upsert-stdin-pddocument_information failed: exit status=$?"
exit 0
